<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Pragma" content="no-cache">
<meta http-equiv="Expires" content="-1">
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<link rel="stylesheet" href="/css/menu.css" type="text/css">
<link rel="stylesheet" href="/css/normal_ws.css" type="text/css">
<link rel="stylesheet" href="/css/line.css" type="text/css">
<script language="javascript" src="/js/language.js"></script>
<script language="javascript" src="/js/jcommon.js"></script>
<script language="javascript" src="/js/jquery.min.js"></script>
<script language="javascript" src="/js/json2.min.js"></script>
<script language="javascript" src="/js/spec.js"></script>
</head>
<body class="mainbody">
<div id="languageDiv" style="display:none">
	<table width="172" border="0" cellpadding="3" cellspacing="0">
	    <tr><td colspan="2" height="12"></td></tr>
  		<tr>
	  		<td id="languageTitle1" class="languageTitle" onclick="chgLanguage(top.frames['title'].v_lang1)">英文</td>
  			<td><img id="img_language1" src="../images/language_check.gif" border="0"></td>
  		</tr>
	    <tr>
		    <td id="languageTitle2" class="languageTitle" onclick="chgLanguage(top.frames['title'].v_lang2)">简体中文</td>
		    <td><img id="img_language2" src="../images/language_no_check.gif" border="0"></td>
	    </tr>
    </table>
</div>
<script>showContainer()</script>
<form method="post" name="ntpCfg" id="ntpCfg">
<input type="hidden" name="ntpcurrenttime" id="ntpcurrenttime" >
<table border=0 width="100%"> 
<tr><td class="content_title"><script>dw(MM_ntp_setting)</script></td></tr>
<tr id="div_content_help"><td class="content_help"><script>dw(MSG_ntp_setting)</script></td></tr>
<tr><td><hr size=1 noshade align=top class=bline></td></tr>
</table>

<table border=0 width="100%">
<tr id="div_date_cn">
<td class="item_left"><script>dw(MM_current_time)</script></td>
<td><input type="text" style="width:44px" maxlength="4" name="cn_yy"> -
<input type="text" style="width:28px" maxlength="4" name="cn_mo"> -
<input type="text" style="width:28px" maxlength="2" name="cn_dd">&nbsp;&nbsp;
<input type="text" style="width:28px" maxlength="2" name="cn_hh"> :
<input type="text" style="width:28px" maxlength="2" name="cn_mi"> :
<input type="text" style="width:28px" maxlength="2" name="cn_ss"><br> (<script>dw(MM_date_chinese)</script>)</td>
</tr>
<!-- <tr id="div_date_en" style="display:none">
<td class="item_left"><script>dw(MM_current_time)</script></td>
<td><input type="text" style="width:28px" maxlength="2" name="en_mo"> -
<input type="text" style="width:28px" maxlength="2" name="en_dd"> -
<input type="text" style="width:44px" maxlength="4" name="en_yy">&nbsp;&nbsp;
<input type="text" style="width:28px" maxlength="2" name="en_hh"> :
<input type="text" style="width:28px" maxlength="2" name="en_mi"> :
<input type="text" style="width:28px" maxlength="2" name="en_ss"><br> (<script>dw(MM_date_english)</script>)</td>
</tr> -->
<tr>
<td class="item_left">&nbsp;</td>
<td><script>dw('<input type="button" value="'+BT_copy_pc_time+'" name="manNTPSyncWithHost" onClick="syncWithHost()">')</script></td>
</tr>
</table>

<table border=0 width="100%"> 
<tr><td><hr size=1 noshade align=top class=bline></td></tr>
<tr><td height="10"></td></tr>
<tr><td align="right"><script>dw('<input type=button class=button value="'+BT_apply+'" onClick="doSubmit()">')</script></td></tr>
</table>
</form>
<script>showFooter()</script>
<script>
var time_tmp = 0;

$(function(){
	init();	
});	

function init() {
	var _html = '';
	$.ajax({
		url: '/webapi',
		type: 'POST',
		dataType: 'json',
		data: '{"action":"getGwTime"}',
		success:function(data){
			console.log(data);
			if (9999 == data.rescode){
				issetLogin();
			}
			if (0 == data.rescode) {
				var time = data.data.Time;
				setJSONValue({
					'cn_yy'	: time.substr(0,4),
					'cn_mo'	: time.substr(4,2),
					'cn_dd' : time.substr(6,2),
					'cn_hh' : time.substr(8,2),
					'cn_mi' : time.substr(10,2),
					'cn_ss' : time.substr(12,2)
				});
			}
		}
	});
}

function syncWithHost(){
	var currentTime = new Date();
	var seconds     = currentTime.getSeconds();
	var minutes     = currentTime.getMinutes();
	var hours       = currentTime.getHours();
	var month       = currentTime.getMonth() + 1;
	var day         = currentTime.getDate();
	var year        = currentTime.getFullYear();

	var seconds_str = " ";
	var minutes_str = " ";
	var hours_str   = " ";
	var month_str   = " ";
	var day_str     = " ";
	var year_str    = " ";

	if(seconds < 10)
		seconds_str = "0" + seconds;
	else
		seconds_str = ""+seconds;

	if(minutes < 10)
		minutes_str = "0" + minutes;
	else
		minutes_str = ""+minutes;

	if(hours < 10)
		hours_str = "0" + hours;
	else
		hours_str = ""+hours;

	if(month < 10)
		month_str = "0" + month;
	else
		month_str = ""+month;

	if(day < 10)
		day_str = "0" + day;
	else
		day_str = day;

	setJSONValue({
		'cn_yy'	: year,
		'cn_mo'	: month_str,
		'cn_dd' : day_str,
		'cn_hh' : hours_str,
		'cn_mi' : minutes_str,
		'cn_ss' : seconds_str,
		'en_yy'	: year,
		'en_mo'	: month_str,
		'en_dd' : day_str,
		'en_hh' : hours_str,
		'en_mi' : minutes_str,
		'en_ss' : seconds_str
	});
	var tmp ='' + year + month_str + day_str + hours_str + minutes_str + seconds_str;
	return tmp;
}

function doSubmit(){
	var year    = $(':input[name="cn_yy"]').val();
	var month   = $(':input[name="cn_mo"]').val();
	var day     = $(':input[name="cn_dd"]').val();
	var hours   = $(':input[name="cn_hh"]').val();
	var minutes = $(':input[name="cn_mi"]').val();

	var seconds_str = "";
	var minutes_str = "";
	var hours_str   = "";
	var month_str   = "";
	var day_str     = "";
	var year_str    = "";
	if (!(year && month && day && hours && minutes )) 
	{
		alert('请输入完整的时间！');
		return false;
	}

	if(1 == minutes.length && minutes < 10){
		minutes_str = "0" + minutes;
	} else {
		minutes_str = ""+minutes;
	}

	if(1 == hours.length && hours < 10){
		hours_str = "0" + hours;
	} else {
		hours_str = ""+hours;
	}

	if(1 == month.length && month < 10){
		month_str = "0" + month;
	} else {
		month_str = ""+month;
	}

	if(1 == day.length && day < 10){
		day_str = "0" + day;
	} else {
		day_str = day;
	}

	var tmp ='' + year + month_str + day_str + hours_str + minutes_str;
	var sub_data = {"action":"setGwTime","data":{"Time":tmp}};
	console.log(sub_data);
	sub_data = JSON.stringify(sub_data);
	$(":input").attr('disabled',true);
	$.ajax({
		url: '/webapi',
		type: 'POST',
		dataType: 'json',
		data: sub_data,
		success:function(data){
			if (9999 == data.rescode){
				issetLogin();
			}
			if (0 == data.rescode) {
				alert('修改时间成功！');
				setTimeout(function(){
				    location.href = location.href;
				},2000);
			} else {
				alert('修改时间失败！'+data_msg_json[data.rescode]);
			}
			$(":input").attr('disabled',false);
		}
	});
}
</script>
</body></html>