<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html>
<head>
	<meta http-equiv="Pragma" content="no-cache">
	<meta http-equiv="Expires" content="-1">
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
	<link rel="stylesheet" href="/css/menu.css" type="text/css">
	<link rel="stylesheet" href="/css/normal_ws.css" type="text/css">
	<link rel="stylesheet" href="/css/line.css" type="text/css">
	<script language="javascript" src="/js/language.js"></script>
	<script language="javascript" src="/js/jcommon.js"></script>
	<script language="javascript" src="/js/jquery.min.js"></script>
	<script language="javascript" src="/js/json2.min.js"></script>
	<script language="javascript" src="/js/spec.js"></script>
	<script language="javascript">
	function saveChanges(){
		if (!checkVaildVal.IsVaildString($("#oldadmpass").val(), MM_oldpassword,1)) return false;
			if (!checkVaildVal.IsVaildString($("#admpass").val(), MM_newpassword,1)) return false;
		if ($("#admpass2").val() != $("#admpass").val()) {alert(JS_msg50);return false;}
		return true;
	}
	function doSubmit(){
		if(saveChanges()==false) return false;
		var data = {};
		data['NewPassword'] = $("#admpass").val();
		data['OldPassword'] = $("#oldadmpass").val();
		var postVar ={"action":"changePassword","data":data};
		uiPost2(postVar);
	}
	function uiPost2(postVar){
		postVar = JSON.stringify(postVar);
		$(":input").attr('disabled',true);
		$.ajax({
			url: '/webapi',
			type: 'POST',
			dataType: 'json',
			data: postVar,
			success:function(data){
				if (9999 == data.rescode){
					issetLogin();
				}
				if (0 == data.rescode) {
					alert('修改密码成功！');
				} else {
					alert('修改密码失败！'+data_msg_json[data.rescode]);
				}
				$(":input").attr('disabled',false);
			}
		});
	}
	</script>
</head>
<body class="mainbody">
	<div id="languageDiv" style="display:none">
		<table width="172" border="0" cellpadding="3" cellspacing="0">
			<tr><td colspan="2" height="12"></td></tr>
			<tr>
				<td id="languageTitle1" class="languageTitle" onclick="chgLanguage(top.frames['title'].v_lang1)">英文</td>
				<td><img id="img_language1" src="../images/language_check.gif" border="0"></td>
			</tr>
			<tr>
				<td id="languageTitle2" class="languageTitle" onclick="chgLanguage(top.frames['title'].v_lang2)">简体中文</td>
				<td><img id="img_language2" src="../images/language_no_check.gif" border="0"></td>
			</tr>
		</table>
	</div>
	<script>showContainer()</script>
	<form method="post" name="passwordCfg" id="passwordCfg">
		<table border=0 width="100%">
			<tr><td class="content_title"><script>dw(MM_admin_setting)</script></td></tr>
			<tr id="div_content_help"><td class="content_help"><script>dw(MSG_sdmin_setting)</script></td></tr>
			<tr><td><hr size=1 noshade align=top class=bline></td></tr>
		</table>
		<table border=0 width="100%">
			<tr>
				<td class="item_left"><script>dw(MM_oldpassword)</script></td>
				<td><input type="text" id="oldadmpass" name="oldadmpass" maxlength="32"></td>
			</tr>
			<tr>
				<td class="item_left"><script>dw(MM_password)</script></td>
				<td><input type="text" id="admpass" name="admpass" maxlength="32"></td>
			</tr>
			<tr>
				<td class="item_left"><script>dw(MM_cfpassword)</script></td>
				<td><input type="text" name="admpass2" id="admpass2" maxlength="32"></td>
			</tr>
		</table>
		<table border=0 width="100%">
			<tr><td><hr size=1 noshade align=top class=bline></td></tr>
			<tr><td height="10"></td></tr>
			<tr><td align="right"><script>dw('<input type=button class=button value="'+BT_apply+'" onClick="doSubmit()">')</script></td></tr>
		</table>
	</form>
	<script>showFooter()</script>
</body></html>