
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<head>
<title></title>
<meta http-equiv="Pragma" content="no-cache">
<meta http-equiv="Expires" content="-1">
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<link rel="stylesheet" href="/css/menu.css" type="text/css">
<link rel="stylesheet" href="/css/normal_ws.css" type="text/css">
<link rel="stylesheet" href="/css/line.css" type="text/css">
<script language="javascript" src="/js/language.js"></script>
<script language="javascript" src="/js/jcommon.js"></script>
<script language="javascript" src="/js/jquery.min.js"></script>
<script language="javascript" src="/js/json2.min.js"></script>
<script language="javascript" src="/js/spec.js"></script>
<script language="javascript">
var responseJson,responseJsonShow;
function clearLogClick(){
	var postVar ={"topicurl":"setting/clearSyslog"};
	uiPost(postVar);
}
function refreshLogClick(){
	window.location.reload();
}
function initValue(){	
	var syslog=responseJsonShow['Syslog'];
	if (responseJson['syslogEnabled'] == 1) {
		$("#syslogEnbl")[0].selectedIndex = 1;
		$("#div_log").show();
		if(navigator.userAgent.indexOf("MSIE")>0) 
			if(navigator.userAgent.indexOf("MSIE 10.0")<0) 
				syslog=syslog.replace(/\n/g,"<br/>");
		$("#syslog").html(syslog);
	}else{
		$("#syslogEnbl")[0].selectedIndex = 0;
		$("#div_log").hide();
	}
}
$(function(){
	// var postVar0 = {topicurl : "setting/getSyslogCfg"};
	// postVar0 = JSON.stringify(postVar0);
	// var postVar1 = {topicurl : "setting/showSyslog"};
	// postVar1 = JSON.stringify(postVar1);
	// $.when($.post("/cgi-bin/cstecgi.cgi", postVar0),
 //            $.post("/cgi-bin/cstecgi.cgi", postVar1))
 //    .done(function( Data0, Data1 ) {
	// 	responseJson = JSON.parse(Data0[0]);
	// 	responseJsonShow = JSON.parse(Data1[0]);
	// 	initValue();
 //    })
	// .fail(function(){
	// 	resetForm();
	// });
   return;
});
function doSubmit(){
	var postVar ={"topicurl":"setting/setSyslogCfg"};
	postVar['syslogEnbl']  = $('#syslogEnbl').val();
	uiPost(postVar);
}
</script>
</head>
<body class="mainbody">
<div id="languageDiv" style="display:none">
	<table width="172" border="0" cellpadding="3" cellspacing="0">
	    <tr><td colspan="2" height="12"></td></tr>
  		<tr>
	  		<td id="languageTitle1" class="languageTitle" onclick="chgLanguage(top.frames['title'].v_lang1)">英文</td>
  			<td><img id="img_language1" src="../images/language_check.gif" border="0"></td>
  		</tr>
	    <tr>
		    <td id="languageTitle2" class="languageTitle" onclick="chgLanguage(top.frames['title'].v_lang2)">简体中文</td>
		    <td><img id="img_language2" src="../images/language_no_check.gif" border="0"></td>
	    </tr>
    </table>
</div>
<script>showContainer()</script>
<form method=post name="syslog">
<table border=0 width="100%"> 
<tr><td class="content_title"><script>dw(MM_syslog)</script></td></tr>
<tr><td class="content_help"><script>dw(MSG_syslog)</script></td></tr>
<tr><td><hr size=1 noshade align=top class=bline></td></tr>
</table>

<table border=0 width="100%">
<tr>
<td class="item_left"><script>dw(MM_onoff)</script></td>
<td><select id="syslogEnbl" name="syslogEnbl">
<option value="0"><script>dw(MM_disable)</script></option>
<option value="1"><script>dw(MM_enable)</script></option>
</select></td>
</tr>
</table>

<table border=0 width="100%"> 
<tr><td><hr size=1 noshade align=top class=bline></td></tr>
<tr><td height="10"></td></tr>
<tr><td align="right"><script>dw('<input type=button class=button value="'+BT_apply+'" onClick="doSubmit()">')</script></td></tr>
</table>
</form>

<div id="div_log" style="display:none">
<form method="post" name="clearLog" >
<table border=0 width="100%">
<tr><td><textarea name="syslog" id="syslog" style="font-size:9pt;width:100%" rows="20" wrap="off" readonly></textarea></td></tr>
</table>

<table border=0 width="100%"> 
<tr><td><hr size=1 noshade align=top class=bline></td></tr>
<tr><td height="10"></td></tr>
<tr><td align="right"><script>dw('<input type="button" class=button value="'+BT_clear+'" onClick="clearLogClick()"> &nbsp; &nbsp;\
<input type="button" class=button value="'+BT_refresh+'" onClick="return refreshLogClick()">')</script></td></tr>
</table>
</form>
</div>
<script>showFooter()</script>
</body></html>
