#!/bin/sh

# Copyright (C) 2014 Deciso B.V.
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice,
#    this list of conditions and the following disclaimer.
#
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES,
# INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY
# AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
# AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY,
# OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.

# load standard rc
echo "csui_enable=\"YES\"">/etc/rc.conf.d/csui
. /etc/rc.subr

name=csui
rcvar=csui_enable
start_precmd=""
start_cmd="${name}_start"
stop_cmd="${name}_stop"

[ -z "$csui_enable" ]       && csui_enable="NO"

csui_prestart()
{
}

csui_start()
{
    if [ -f /var/run/lighty-webConfigurator-cs.pid ]; then
        echo "stop csui process"
        /bin/pkill -TERM -F /var/run/lighty-webConfigurator-cs.pid
    fi
    if [ -f /var/run/lighty-webConfigurator.pid ]; then
        echo "stop web process"
		/bin/pkill -TERM -F /var/run/lighty-webConfigurator.pid
	fi
	echo "start csui process"
	/bin/cp -rf /usr/local/opnsense/cs/conf/lighty-webConfigurator-cs.conf /var/etc/
	/usr/local/sbin/lighttpd -f /var/etc/lighty-webConfigurator-cs.conf
	if [ ! -f /usr/local/opnsense/cs/www/public/js/spec.js ];then
	    /bin/sleep 3;/usr/local/bin/curl http://127.0.0.1/webapi/generror>/tmp/generror.log &
	fi
}

csui_stop()
{
    if [ -f /var/run/lighty-webConfigurator-cs.pid ]; then
        echo "stop csui process"
        /bin/pkill -TERM -F /var/run/lighty-webConfigurator-cs.pid
    fi
    if [ -f /var/run/lighty-webConfigurator.pid ]; then
        echo "stop web process"
        /bin/pkill -TERM -F /var/run/lighty-webConfigurator.pid
    fi
    echo "start web process"
    /usr/local/sbin/lighttpd -f /var/etc/lighty-webConfigurator.conf
}

load_rc_config $name
run_rc_command $1
