<html><head>
    <meta http-equiv="Pragma" content="no-cache">
    <meta http-equiv="Expires" content="-1">
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <link rel="stylesheet" href="/css/menu.css" type="text/css">
    <link rel="stylesheet" href="/css/normal_ws.css" type="text/css">
    <style>
        #div_staticDhcpList {text-align: center;}
        #div_staticDhcpList tr:nth-child(2n){background-color: #f1f1f1;}
        #div_staticDhcpList tr td:nth-child(1){width: 61px;padding:0}
        #div_staticDhcpList tr td:nth-child(2){width: 84px;padding:0}
        #div_staticDhcpList tr td:nth-child(3){width: 105px;padding:0}
        #div_staticDhcpList tr td:nth-child(4){width: 129px;padding:0}
        #div_staticDhcpList tr td:nth-child(5){width: 130px;padding:0}
        #div_staticDhcpList tr td:nth-child(6){width: 84px;padding:0}
        #div_staticDhcpList tr td:nth-child(7){width: 84px;padding:0}
        #div_staticDhcpList tr td:nth-child(8){width: 104px;padding:0}
    </style>
    <script language="javascript" src="/js/language.js"></script>
    <script language="javascript" src="/js/jcommon.js"></script>
    <script language="javascript" src="/js/ajax.js"></script>
    <script language="javascript" src="/js/jquery.min.js"></script>
    <script language="javascript" src="/js/json2.min.js"></script>
    <script language="javascript" src="/js/spec.js"></script>
</head>
<body class="mainbody" marginwidth="0" marginheight="0">
<input type="hidden" id="lannum" name="lannum">
<div id="languageDiv" style="display:none"><table width="172" border="0" cellpadding="3" cellspacing="0">
        <tbody>
        <tr><td colspan="2" height="12"></td></tr>
        <tr><td id="languageTitle1" class="languageTitle" onclick="chgLanguage(top.frames['title'].v_lang1)">英文</td>
            <td><img id="img_language1" src="../style/language_check.gif" border="0"></td></tr>
        <tr><td id="languageTitle2" class="languageTitle" onclick="chgLanguage(top.frames['title'].v_lang2)">简体中文</td>
            <td><img id="img_language2" src="../style/language_no_check.gif" border="0"></td></tr>
        </tbody></table>
</div>
<table width="700"><tbody><tr><td>
            <form name="formStaticDhcpDel" id="formStaticDhcpDel">
                <table border="0" width="100%">
                    <tbody><tr><td colspan="8"><b>登陆用户列表</b></td></tr>
                    <tr><td colspan="8"><hr size="1" noshade="" align="top" class="bline"></td></tr>
                    <tr align="center">
                        <td class="item_center"><b>ID</b></td>
                        <td class="item_center"><b>用户名</b></td>
                        <td class="item_center"><b>IP地址</b></td>
                        <td class="item_center"><b>MAC</b></td>
                        <td class="item_center"><b>上传的流量</b></td>
                        <td class="item_center"><b>下载的流量</b></td>
                        <td class="item_center"><b>最后上网时间</b></td>
                        <td class="item_center"><b>操作</b></td>
                    </tr>
                    <tbody id="div_staticDhcpList"></tbody>
                    </tbody>
                </table>

                <table border="0" width="100%">
                    <tbody><tr><td><hr size="1" noshade="" align="top" class="bline"></td></tr></tbody>
                </table>
            </form>
            <script>showFooter()</script></td></tr></tbody></table>
<iframe id="win78iframe" class="hidden" name="win78target"></iframe>
<script>
    $(function(){
        get_route_();
    });
    function get_route_() {
        $.ajax({
            url: '/webapi',
            type: 'POST',
            dataType: 'json',
            data: '{"action":"getPortalSessions", "data":{}}',
            success:function(data){
                if (9999 == data.rescode){
                    issetLogin();
                }
                var _html = '';
                if (0 == data.rescode) {
                    var data = data.data;
                    if (0 < data.length) {
                        for (var i = 0; i < data.length; i++) {
                            _html += "<tr align='center' >";
                            _html += "<td>"+(i+1)+"</td>";
                            _html += "<td>"+data[i].Username+"</td>";
                            _html += "<td>"+data[i].Ip+"</td>";
                            _html += "<td>"+data[i].Mac+"</td>";
                            _html += "<td>"+data[i].UpBytes+"</td>";
                            _html += "<td>"+data[i].DownBytes+"</td>";
                            _html += "<td>"+data[i].LastAccess+"</td>";
                            _html += '<td width=12%><input type="button" value="下线" id='+data[i].Sessionid+' name=name_route onclick="off_route_click(this)" /></td>';
                            _html += "</tr>";
                        }
                        $('#div_staticDhcpList').html(_html);
                    } else {
                        $('#div_staticDhcpList').html('<tr><td colspan=7>暂无数据！</td></tr>');
                    }
                }
            }
        });
    }
    
    function off_route_click(th) {
        var sessionid = th.id;
        var one_route_msg = {};
        one_route_msg.Sessionid = sessionid;
        var sub_data = {"action":"delPortalSession", "data":one_route_msg};
        sub_data = JSON.stringify(sub_data);
        console.log(sub_data);
        $(":input").attr('disabled',true);
        $.ajax({
            url: '/webapi',
            type: 'POST',
            dataType: 'json',
            data: sub_data,
            success:function(data){
                if (9999 == data.rescode){
                    issetLogin();
                }
                console.log(data);
                if (0 == data.rescode) {
                    alert('下线成功！');
                    location.href = location.href;
                } else {
                    alert('下线失败！'+data_msg_json[data.rescode]);
                }
                $(":input").attr('disabled',false);
            }
        })
    }
</script>
</body>
</html>

