<html><head>
	<meta http-equiv="Pragma" content="no-cache">
	<meta http-equiv="Expires" content="-1">
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
	<link rel="stylesheet" href="/css/menu.css" type="text/css">
	<link rel="stylesheet" href="/css/normal_ws.css" type="text/css">
	<style>
	#div_staticDhcpList {text-align: center;}
	#div_staticDhcpList tr:nth-child(2n){background-color: #f1f1f1;}
	#div_staticDhcpList tr td:nth-child(1){width: 61px;padding:0}
	#div_staticDhcpList tr td:nth-child(2){width: 84px;padding:0}
	#div_staticDhcpList tr td:nth-child(3){width: 105px;padding:0}
	#div_staticDhcpList tr td:nth-child(4){width: 129px;padding:0}
	#div_staticDhcpList tr td:nth-child(5){width: 130px;padding:0}
	#div_staticDhcpList tr td:nth-child(6){width: 84px;padding:0}
	#div_staticDhcpList tr td:nth-child(7){width: 85px;padding:0}
	</style>
	<script language="javascript" src="/js/language.js"></script>
	<script language="javascript" src="/js/jcommon.js"></script>
	<script language="javascript" src="/js/ajax.js"></script>
	<script language="javascript" src="/js/jquery.min.js"></script>
	<script language="javascript" src="/js/json2.min.js"></script>
	<script language="javascript" src="/js/spec.js"></script>
	<script language="javascript">
var responseJson, responseJsonLan,responseJson2,JsonInterfaceList;
var rules_num, v_lanip, v_lanmsk, v_enabled, v_dhcpEnd, v_dhcpStart;
var arr_ip, arr_mac, arr_cmnt,flag=0,obj=1;
window.onerror=function(){return true;} 
function disableAddFiled(){	
	$("#mac1, #mac2, #mac3, #mac4, #mac5, #mac6, #comment").attr("disabled",true);
	$("#ip_address0,#ip_address1,#ip_address2,#ip_address3,#lan_num").attr("disabled",true);
	$("#add, #scan").attr("disabled",true);
}
function disableDelButton(){	
	$("#del_sel, #delreset").attr("disabled",true);
}
function initValue(val){
	v_lanip=responseJson['lanIp'];
	v_lanmsk=responseJson['lanNetmask'];
	v_enabled=responseJson['enable'];		
	rules_num=responseJson['RuleNum'];
	v_dhcpStart=responseJsonLan['dhcpStart'];
	v_dhcpEnd=responseJsonLan['dhcpEnd'];
	if (v_enabled==0) {
		disableAddFiled();
		disableDelButton();
	}
	if(v_enabled==1)
		$("#enabled")[0].selectedIndex=1;
	else 
		$("#enabled")[0].selectedIndex=0;	
	
	if (rules_num == 0)
		disableDelButton();
	else{
		arr_ip = responseJson['IpRules'].split(";");
		arr_mac = responseJson['MacRules'].split(";");
		arr_cmnt = responseJson['Comments'].split(";");
	}
//	if (v_lanip !="") 
//		decomIP2($(":input[name=ips]"),v_lanip,0);
	
	var dhcpListTab=$("#div_staticDhcpList").get(0);
	var trNode;
if(!flag)
{
	for(var i=1; i<parseInt(rules_num)+1; i++){
		trNode=dhcpListTab.insertRow(-1);
		trNode.align="center";
		trNode.insertCell(0).innerHTML = i;
		trNode.insertCell(1).innerHTML = arr_ip[i-1];
		trNode.insertCell(2).innerHTML = arr_mac[i-1];
		trNode.insertCell(3).innerHTML = arr_cmnt[i-1];
		trNode.insertCell(4).innerHTML = '<input type=\"checkbox\" id=id_'+(i-1)+' name=name_'+(i-1)+' value=value_'+(i-1)+'>';		
	}
}
	
	var count = 0;
	if(v_lanmsk !=""){
		var msk = v_lanmsk.split(".");
		for(var k=0; k<4; k++){
			if(msk[k] == "255"){	
				setDisabled("#ip_address"+k, true);
				count++;
			}
		}
	}
	if (v_lanip !="") decomIP2($(":input[name=ips]"),v_lanip,0,count);
	if(val != 0)
		createRulesTable(val);
	else
		createRulesTable($('#lannum').val());
}
$(function(){
	// var postVar = {topicurl : "setting/getStaticDhcpConfig"};
	// postVar = JSON.stringify(postVar);
	// var postVar1 = {topicurl : "setting/getLanConfig"};
	// postVar1 = JSON.stringify(postVar1);
	
	// var postVar2 = { topicurl : "setting/getlanCurInterface"};
	// postVar2 = JSON.stringify(postVar2);

	// $.ajax({
	// 		type: "post",
	// 		url: " /cgi-bin/cstecgi.cgi",
	// 		data: postVar2,
	// 		async: false,
	// 		success: function(Data2) {
	// 			JsonInterfaceList = JSON.parse(Data2);
	// 		}
	// 	});
			
	// $.when( $.post("/cgi-bin/cstecgi.cgi", postVar),
	// 		$.post("/cgi-bin/cstecgi.cgi", postVar1))
 //    .done(function( Data, Data1) {
	// 	responseJson = JSON.parse(Data[0]);
	// 	responseJsonLan = JSON.parse(Data1[0]);
	// 	initValue();
	// })
	// .fail(function(){
	// 	resetForm();
	// });
	return;
});


function createRulesTable(val){
	var tmpJson;
	var Tmp="",interface_num;

	interface_num=JsonInterfaceList.length;
	for(i=0;i<interface_num;i++)
	{
		tmpJson=JsonInterfaceList[i];
		if(tmpJson.enabled == "1")
			if((i+1) == val)
				Tmp+="<option selected value="+(i+1)+">"+"LAN"+(i+1)+"</option>";
			else
				Tmp+="<option value="+(i+1)+">"+"LAN"+(i+1)+"</option>";
	}
	
	if(Tmp == "")
	{
		FLAG=1;
		Tmp+="<option selected value=\"0\">"+"LAN1"+"</option>";
		$("#lan_num").html(Tmp);
		setDisabled("#lan_num",true);
	}
	else
	{
		$("#lan_num").html(Tmp);
	}
	
}

function updateState(){
	if ($("#enabled").val()=="0") {
		disableAddFiled();
		disableDelButton();
	}

	var postVar ={"topicurl":"setting/setStaticDhcpConfig"};
	postVar['enabled']= $("#enabled").val();
	postVar['addEffect']= "1";
	uiPost(postVar);
}

function updateState_2(){	
	flag = 1;
	obj=$("#lan_num").val();
	var postVar = {topicurl : "setting/getStaticDhcpConfig"};
	postVar['lanIndex']= $("#lan_num").val();
	postVar = JSON.stringify(postVar);
	var postVar1 = {topicurl : "setting/getLanConfig"};
	postVar1['lanIndex']= $("#lan_num").val();
	postVar1 = JSON.stringify(postVar1);
	
	var postVar2 = { topicurl : "setting/getlanCurInterface"};
	postVar2 = JSON.stringify(postVar2);

	$.ajax({
			type: "post",
			url: " /cgi-bin/cstecgi.cgi",
			data: postVar2,
			async: false,
			success: function(Data2) {
				JsonInterfaceList = JSON.parse(Data2);
			}
		});
			
	$.when( $.post("/cgi-bin/cstecgi.cgi", postVar),
			$.post("/cgi-bin/cstecgi.cgi", postVar1))
    .done(function( Data, Data1) {
		responseJson = JSON.parse(Data[0]);
		responseJsonLan = JSON.parse(Data1[0]);
		initValue($("#lan_num").val());
	})
	.fail(function(){
		resetForm();
	});

}

function deleteClick(){
	var postVar="", delIndex = "";
	var delNum = 0;
	
	postVar ={"topicurl":"setting/delStaticDhcpConfig"};
	for (i=0; i< rules_num; i++) {
		var tmpNode=$("#id_"+i).get(0);
		if (tmpNode.checked == true){
			delIndex += (i+";");
			delNum++;
		}
  	}
	if(delNum == 0){
		alert(JS_msg36);
		return false;
	}
	delIndex = delIndex.substring(0, delIndex.length-1);
	postVar['delIndex'] = delIndex;
	postVar['delNum'] = delNum;
	uiPost(postVar);
}
function saveChanges(){
	if (rules_num >= 40){
		alert(JS_msg28);
		return false;
	}
	setJSONValue({	
		'ip_address' : combinIP($(":input[name=ips]"))
	});
	
	var netip=v_lanip.replace(/\.\d{1,3}$/,".");
	$("#ip_address").val(netip+$("#ip").val());	
	if (!checkVaildVal.IsVaildIpAddr($("#ip_address").val(), MM_ipaddr)) return false;
	if (!checkVaildVal.IsSameIp($("#ip_address").val(), v_lanmsk, v_lanip)) {alert(JS_msg38);return false;}
	if (!checkVaildVal.IsIpSubnet($("#ip_address").val(), v_lanmsk, v_lanip)) {alert(JS_msg38);return false;}
	if (checkVaildVal.IsNotDhcpPool(v_dhcpStart, v_dhcpEnd,$("#ip_address").val())){alert(JS_msg164); return false;}
	if ($("#ip_address").val()== v_lanip) {alert(JS_msg39);return false;}
	
	var mac_tmp=combinMAC2($("#mac1").val(),$("#mac2").val(),$("#mac3").val(),$("#mac4").val(),$("#mac5").val(),$("#mac6").val());
	$("#mac_address").val(mac_tmp);
	if (!checkVaildVal.IsVaildMacAddr($("#mac_address").val()))
		return false;
	
	for (var i=0; i<rules_num; i++){
		if (($("#mac_address").val()==arr_mac[i]) || 
			($("#mac_address").val().toLowerCase()==arr_mac[i].toLowerCase()) || 
			($("#ip_address").val()==arr_ip[i])) {
			alert(JS_msg29);
			return false;
		}
	}
	if ($("#comment").val()!=""){if (!checkVaildVal.IsVaildString($("#comment").val(), MM_comment,2)) return false;}	
	return true;
}
function doSubmit(){
	if (saveChanges()==false)
		return false;
	
	var postVar ={"topicurl":"setting/setStaticDhcpConfig"};
	postVar['enabled']   = $("#enabled").val();
	postVar['addIp']     = $("#ip_address").val();
	postVar['addMac']    = $("#mac_address").val();
	postVar['addCmnt']   = $("#comment").val();
	postVar['addEffect'] = "0";
	//postVar['lanIndex']= $("#lan_num").val();
	
	uiPost(postVar);
}
function resultFun(data){
	if(data=="" || data==null)
		win78reload();
	else
		window.location.href='/internet/static_dhcp.asp';
}
function errorFun(readyState,status){win78reload();}
function win78reload(){setTimeout(function(){Ajax.getInstance('/login.asp','',0,resultFun,errorFun);Ajax.get();},"5000");}
function arpTblClick(){
	url="../firewall/arpinfo.asp#flag=5#mode="+obj
	openWindow(url,"_blank",700,400);
}
</script>

</head>
<body class="mainbody" marginwidth="0" marginheight="0">
	<input type="hidden" id="lannum" name="lannum">
	<div id="languageDiv" style="display:none"><table width="172" border="0" cellpadding="3" cellspacing="0">
	<tbody>
		<tr><td colspan="2" height="12"></td></tr>
		<tr><td id="languageTitle1" class="languageTitle" onclick="chgLanguage(top.frames['title'].v_lang1)">英文</td>
		<td><img id="img_language1" src="../style/language_check.gif" border="0"></td></tr>
		<tr><td id="languageTitle2" class="languageTitle" onclick="chgLanguage(top.frames['title'].v_lang2)">简体中文</td>
		<td><img id="img_language2" src="../style/language_no_check.gif" border="0"></td></tr>
	</tbody></table>
	</div>
	<table width="700"><tbody><tr><td>
	<form name="formStaticDhcpAdd" id="formStaticDhcpAdd">
		<input type="hidden" id="addEffect" name="addEffect" value="1">
		<table border="0" width="100%">
			<tbody><tr><td class="content_title"><script>dw(MM_routing)</script></td></tr>
			<tr id="div_content_help"><td class="content_help">静态路由设置。通过手动设置ip的路由规则。</td></tr>
			<tr><td><hr size="1" noshade="" align="top" class="bline"></td></tr>
		</tbody></table>
		<table border="0" width="100%" style="display: none;">
			<tbody><tr>
				<td class="item_left"><script>dw(MM_onoff)</script></td>
				<td><select id="enabled" name="enabled" onchange="updateState()">
					<option value="0"><script>dw(MM_disable)</script></option>
					<option value="1"><script>dw(MM_enable)</script></option>
				</select></td>
			</tr>
			<tr><td colspan="2"><hr size="1" noshade="" align="top" class="bline"></td></tr>
		</tbody></table>
		<br>
		<table border="0" width="100%">
			<tbody><tr><td colspan="2"><b><script>dw(MM_add_rule)</script></b></td>
			</tr><tr id="div_addline"><td colspan="2"><hr size="1" noshade="" align="top" class="bline"></td></tr>
			<tr>
			</tr><tr style="display: none;">
			<td class="item_left"><script>dw(MM_policy_specify)</script></td>
			<td><select id="lan_num" name="lan_num" onchange="updateState_2()" disabled="disabled"><option value="1">LAN1</option></select></td>
		</tr>
		<tr><td class="item_left"><script>dw(MM_interface)</script></td>
		<td><select name="route_interface" id="route_interface"> </select> </td>
	</tr>
	<tr>
        <td class="item_left_"> <script> dw(MM_ipaddr) </script> </td>
        <td><input type="hidden" id="ip_address" name="ip_address">
		<input type="text" style="width:33px" maxlength="3" id="ip_address0" name="ips" onkeydown="return ipVali(event,this.name,0);" >
		.
		<input type="text" style="width:33px" maxlength="3" id="ip_address1" name="ips" onkeydown="return ipVali(event,this.name,1);" >
		.
		<input type="text" style="width:33px" maxlength="3" id="ip_address2" name="ips" onkeydown="return ipVali(event,this.name,2);" >
		.
		<input type="text" style="width:33px" maxlength="3" id="ip_address3" name="ips" onkeydown="return ipVali(event,this.name,3);" >
        </td>
    </tr>
    <tr>
        <td class="item_left_"> <script> dw(MM_netmask) </script> </td>
        <td>
            <input type="hidden" id="staticNetmask" name="staticNetmask" value="">
            <input type="text" style="width:33px" maxlength="3" name="mask" onkeydown="return ipVali(event,this.name,0);">
            .
            <input type="text" style="width:33px" maxlength="3" name="mask" onkeydown="return ipVali(event,this.name,1);">
            .
            <input type="text" style="width:33px" maxlength="3" name="mask" onkeydown="return ipVali(event,this.name,2);">
            .
            <input type="text" style="width:33px" maxlength="3" name="mask" onkeydown="return ipVali(event,this.name,3);">
        </td>
    </tr>
    <tr>
        <td class="item_left_"> <script> dw(MM_default_gateway) </script> </td>
        <td>
            <input type="hidden" id="staticGateway" name="staticGateway" value="">
            <input type="text" style="width:33px" maxlength="3" name="gateway" onkeydown="return ipVali(event,this.name,0);">
            .
            <input type="text" style="width:33px" maxlength="3" name="gateway" onkeydown="return ipVali(event,this.name,1);">
            .
            <input type="text" style="width:33px" maxlength="3" name="gateway" onkeydown="return ipVali(event,this.name,2);">
            .
            <input type="text" style="width:33px" maxlength="3" name="gateway" onkeydown="return ipVali(event,this.name,3);">
        </td>
    </tr>
	<tr>
		<td class="item_left"><script>dw(MM_comment)</script></td>
		<td><input type="text" id="comment" name="comment" maxlength="20"></td>
	</tr>
<table border="0" width="100%">
	<tbody><tr><td><hr size="1" noshade="" align="top" class="bline"></td></tr>
	<tr><td height="10"></td></tr>
	<tr><td align="right"><script>dw('<input type=button class=button value="'+BT_add+'" id="add" onClick="cs_do_submit()">')</script></td></tr>
</tbody></table>
</form>
<form name="formStaticDhcpDel" id="formStaticDhcpDel">
<table border="0" width="100%">
	<tbody><tr><td colspan="7"><b><script>dw(MM_routing_table);dw(JS_msg59);</script></b></td></tr>
	<tr><td colspan="7"><hr size="1" noshade="" align="top" class="bline"></td></tr>
	<tr align="center">
		<td class="item_center"><b>ID</b></td>
		<td class="item_center"><b><script>dw(MM_interface)</script></b></td>
		<td class="item_center"><b><script>dw(MM_ipaddr)</script></b></td>
		<td class="item_center"><b><script>dw(MM_netmask)</script></b></td>
		<td class="item_center"><b><script>dw(MM_default_gateway)</script></b></td>
		<td class="item_center"><b><script>dw(MM_comment)</script></b></td>
		<td class="item_center"><b><script>dw(MM_select)</script></b></td>
	</tr>
</tbody></table>
<div style="max-height:250px; overflow:auto">
	<table border="0" width="100%">
	<tbody id="div_staticDhcpList"></tbody>
</table></div>
<table border="0" width="100%">
	<tbody><tr><td><hr size="1" noshade="" align="top" class="bline"></td></tr>
	<tr><td height="10"></td></tr>
	<tr><td align="right">
	<script>
		dw('<input type=button class=button value="'+BT_delete+'" id="del_sel" onClick="del_route_click()">&nbsp;&nbsp;&nbsp;&nbsp;\
			<input type="button" class="button" value="'+BT_reset+'" id="delreset" onClick="resetForm()">')
	</script>
	</td></tr>
</tbody></table>
</form>
<script>showFooter()</script></td></tr></tbody></table>
<iframe id="win78iframe" class="hidden" name="win78target"></iframe>

<script>
	$(function(){
		get_interface();
		get_route_();
	});
	function get_interface() {
		var _html = '';
		$.ajax({
			url: '/webapi',
			type: 'POST',
			dataType: 'json',
			data: '{"action":"getStatusInfo"}',
			success:function(data){
				if (9999 == data.rescode){
					issetLogin();
				}
				if (0 == data.rescode) {
					var interface = data.data.interface;
					$.each(interface,function(index, el) {
						if (el){
							if('LAN1' == index.toUpperCase()){
								_html += '<option value="'+index+'">'+index+'</option>';
							}
						}

					});
					$('#route_interface').html(_html);
				}
			}
		})
	}
	function get_route_() {
		$.ajax({
			url: '/webapi',
			type: 'POST',
			dataType: 'json',
			data: '{"action":"getStaticRoute", "data":{}}',
			success:function(data){
				if (9999 == data.rescode){
					issetLogin();
				}
				var _html = '';
				if (0 == data.rescode) {
					var data = data.data;
					if (0 < data.length) {
						for (var i = 0; i < data.length; i++) {
							_html += "<tr align=center >";
							_html += "<td>"+(i+1)+"</td>";
							_html += "<td>"+data[i].Interface+"</td>";
							_html += "<td>"+data[i].Ip+"</td>";
							_html += "<td>"+data[i].Netmask+"</td>";
							_html += "<td>"+data[i].Gateway+"</td>";
							_html += "<td>"+data[i].Descr+"</td>";
							_html += '<td><input type="checkbox" id=id_route_'+i+' name=name_route data-netmask='+data[i].Netmask+' data-ip='+data[i].Ip+' value='+data[i].Interface+' /></td>';
							_html += "</tr>";
						}
						$('#div_staticDhcpList').html(_html);
					} else {
						$('#div_staticDhcpList').html('<tr><td colspan=5>暂无数据！</td></tr>');
					}
				}
			}
		});
	}

	function cs_do_submit() {
		var data       = {};
		data.Interface = $('#route_interface').val();
		data.Ip        = combinIP($(":input[name=ips]"));
		if (!checkVaildVal.IsVaildIpAddr(data.Ip, MM_ipaddr)) return false;
		
		data.Netmask   = combinIP($(":input[name=mask]"));
		
		data.Gateway   = combinIP($(":input[name=gateway]"));

		data.Descr     = $("#comment").val();

		var sub_data   = {"action":"addStaticRoute", "data":data};
		sub_data       = JSON.stringify(sub_data);
		$('input[type="button"]').attr('disabled',true);
		$.ajax({
			url: '/webapi',
			type: 'POST',
			dataType: 'json',
			data: sub_data,
			success:function(data){
				if (9999 == data.rescode){
					issetLogin();
				}
				if (0 == data.rescode) {
					alert('添加成功！');
				    location.href = location.href;
				} else {
					alert('添加失败！'+data_msg_json[data.rescode]);
				}
				$('input[type="button"]').attr('disabled',false);
			}
		})

	}

	function del_route_click() {
		var dhcp_all = $(':input[name="name_route"]');
		var del_mac = [];
		var one_route_msg = {};
		dhcp_all.each(function(index, el) {
			if (el.checked) {
				one_route_msg.Interface = el.value;
				one_route_msg.Ip        = $(el).data('ip');
				one_route_msg.Netmask   = $(el).data('netmask');
				del_mac.push(one_route_msg);
			}
		});
		if (1 != del_mac.length) {
			alert('只能同时选择删除一条规则！');
			return false;
		}
        var sub_data = {"action":"delStaticRoute", "data":one_route_msg};
        sub_data = JSON.stringify(sub_data);
		$('input[type="button"]').attr('disabled',true);
		$.ajax({
			url: '/webapi',
			type: 'POST',
			dataType: 'json',
			data: sub_data,
			success:function(data){
				if (9999 == data.rescode){
					issetLogin();
				}
				if (0 == data.rescode) {
					alert('删除成功！');
				    location.href = location.href;
				} else {
					alert('删除失败！'+data_msg_json[data.rescode]);
				}
				$('input[type="button"]').attr('disabled',false);
			}
		})
	}
</script>

</body>
</html>

