<html>
<head>
    <title>TOTOLINK</title>
    <meta http-equiv="Pragma" content="no-cache">
    <meta http-equiv="Expires" content="-1">
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <link rel="shortcut icon" href="favicon.ico">
    <script language="javascript" src="/js/jquery.min.js"></script>
    <script language="javascript" src="/js/language.js"></script>
    <script language="javascript" src="/js/jcommon.js"></script>
    <script language="javascript" src="/js/json2.min.js"></script>
</head>
<frameset rows="96,*,40" border="0" framespacing="0" frameborder="NO">
    <frame src="/index/top" name="top" id="topasp" frameborder="NO" scrolling="NO" marginwidth="0" marginheight="0">
    <frameset cols="6,1,*,1,6" border="0" framespacing="0" frameborder="NO">
        <frame frameborder="NO" name=other1 marginWidth=0 marginheight=0 src="/index/empty3"  scrolling=no  noresize>
        <frame src="/index/empty1" name="empty1" marginwidth="0" marginheight="0" scrolling="NO" frameborder="NO">
        <frameset rows="44,*" border="0" framespacing="0" frameborder="NO">
            <frame src="/index/title" id="title" name="title" marginwidth="0" marginheight="0" scrolling="NO" frameborder="NO">
            <frame src="/login" id="title" name="title" marginwidth="0" marginheight="0" scrolling="NO" frameborder="NO">
        </frameset>
        <frame src="/index/empty1" name="empty2" marginwidth="0" marginheight="0" scrolling="NO" frameborder="NO" >
        <frame frameborder="NO" name=other2 marginWidth=0 marginheight=0 src="/index/empty3" scrolling=no  noresize>
    </frameset>
    <frame name="/index/bottom" scrolling="no" noresize="noresize" target="contents" src="/index/bottom">
</frameset>

<noframes>
    <body bgcolor="#FFFFFF" style="overflow-x:hidden;">
    </body></noframes>
</html>
