
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<head>
<meta http-equiv="Pragma" content="no-cache">
<meta http-equiv="Expires" content="-1">
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<link rel="stylesheet" href="/css/menu.css" type="text/css">
<link rel="stylesheet" href="/css/normal_ws.css" type="text/css">
<link rel="stylesheet" href="/css/line.css" type="text/css">
<script language="javascript" src="/js/language.js"></script>
<script language="javascript" src="/js/jcommon.js"></script>
<script language="javascript" src="/js/jquery.min.js"></script>
<script language="javascript" src="/js/json2.min.js"></script>
<script language="javascript" src="/js/spec.js"></script>
<script language="javascript">
var responseJson;
function initValue(){
	setJSONValue({
		"SPIFWEnabled"  : responseJson['SPIFWEnabled'],
		"BlockPortScan" : responseJson['BlockPortScan'],
		"BlockSynFlood" : responseJson['BlockSynFlood']
	});
}
$(function(){
	// var postVar = {topicurl : "setting/getDosCfg"};
	// postVar = JSON.stringify(postVar);
	// $.when( $.post("/cgi-bin/cstecgi.cgi", postVar))
 //    .done(function( Data) {
	// 	responseJson = JSON.parse(Data);
	// 	initValue();
	// })
	// .fail(function(){
	// 	resetForm();
	// });
	return;
});
function doSubmit(){
	var postVar ={"topicurl":"setting/setDosCfg"};
	postVar['SPIFWEnabled'] = $("#SPIFWEnabled").val();
	postVar['BlockPortScan'] = $("#BlockPortScan").val();
	postVar["BlockSynFlood"] = $("#BlockSynFlood").val();
	uiPost(postVar);
}
</script>
</head>
<body class="mainbody">
<div id="languageDiv" style="display:none">
	<table width="172" border="0" cellpadding="3" cellspacing="0">
	    <tr><td colspan="2" height="12"></td></tr>
  		<tr>
	  		<td id="languageTitle1" class="languageTitle" onclick="chgLanguage(top.frames['title'].v_lang1)">英文</td>
  			<td><img id="img_language1" src="../style/language_check.gif" border="0"></td>
  		</tr>
	    <tr>
		    <td id="languageTitle2" class="languageTitle" onclick="chgLanguage(top.frames['title'].v_lang2)">简体中文</td>
		    <td><img id="img_language2" src="../style/language_no_check.gif" border="0"></td>
	    </tr>
    </table>
</div>
<script>showContainer()</script>
<form id="sysFirewall" name="sysFirewall" >
<table border=0 width="100%"> 
<tr><td class="content_title"><script>dw(MM_dos_setting)</script></td></tr>
<tr><td class="content_help"><script>dw(MSG_dos_setting)</script></td></tr>
<tr><td><hr size=1 noshade align=top class=bline></td></tr>
</table>

<table border=0 width="100%">
<tr>
<td class="item_left"><script>dw(MM_spi_firewall)</script></td>
<td><select id="SPIFWEnabled" name="SPIFWEnabled">
<option value="0"><script>dw(MM_disable)</script></option>
<option value="1"><script>dw(MM_enable)</script></option>
</select></td>
</tr>
<tr>
<td class="item_left"><script>dw(MM_block_port_scan)</script></td>
<td><select id="BlockPortScan" name="BlockPortScan">
<option value="0"><script>dw(MM_disable)</script></option>
<option value="1"><script>dw(MM_enable)</script></option>
</select></td>
</tr>
<tr>
<td class="item_left"><script>dw(MM_block_svn_flood)</script></td>
<td><select id="BlockSynFlood" name="BlockSynFlood">
<option value="0"><script>dw(MM_disable)</script></option>
<option value="1"><script>dw(MM_enable)</script></option>
</select></td>
</tr>
</table>

<table border=0 width="100%"> 
<tr><td><hr size=1 noshade align=top class=bline></td></tr>
<tr><td height="10"></td></tr>
<tr><td align="right"><script>dw('<input type=button class=button value="'+BT_apply+'" onClick="doSubmit();">')</script></td></tr>
</table>
</form>
<script>showFooter()</script>
</body></html>