<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<head>
<meta http-equiv="Pragma" content="no-cache">
<meta http-equiv="Expires" content="-1">
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<link rel="stylesheet" href="/css/menu.css" type="text/css">
<link rel="stylesheet" href="/css/normal_ws.css" type="text/css">
<link rel="stylesheet" href="/css/line.css" type="text/css">
<style>

#div_portForwardList {text-align: center;}
#div_portForwardList tr:nth-child(2n){background-color: #f1f1f1;}
#div_portForwardList tr td:nth-child(1){width:59px;padding:0}
#div_portForwardList tr td:nth-child(2){width:98px;padding:0}
#div_portForwardList tr td:nth-child(3){width:121px;padding:0}
#div_portForwardList tr td:nth-child(4){width:78px;padding:0}
#div_portForwardList tr td:nth-child(5){width:122px;padding:0}
#div_portForwardList tr td:nth-child(6){width:122px;padding:0}
#div_portForwardList tr td:nth-child(7){width:80px;padding:0}
</style>
<script language="javascript" src="/js/language.js"></script>
<script language="javascript" src="/js/jcommon.js"></script>
<script language="javascript" src="/js/jquery.min.js"></script>
<script language="javascript" src="/js/json2.min.js"></script>
<script language="javascript" src="/js/spec.js"></script>
</head>
<body class="mainbody">
<input type="hidden" id="lannum" name="lannum">
<div id="languageDiv" style="display:none">
	<table width="172" border="0" cellpadding="3" cellspacing="0">
	    <tr><td colspan="2" height="12"></td></tr>
  		<tr>
	  		<td id="languageTitle1" class="languageTitle" onclick="chgLanguage(top.frames['title'].v_lang1)">英文</td>
  			<td><img id="img_language1" src="../style/language_check.gif" border="0"></td>
  		</tr>
	    <tr>
		    <td id="languageTitle2" class="languageTitle" onclick="chgLanguage(top.frames['title'].v_lang2)">简体中文</td>
		    <td><img id="img_language2" src="../style/language_no_check.gif" border="0"></td>
	    </tr>
    </table>
</div>
<script>showContainer()</script>
<form method=post name="formPortFwdAdd" id="formPortFwdAdd">
<input type="hidden" id="ip_address" name="ip_address">
<input type="hidden" id="addEffect" name="addEffect" value="1">
<table border=0 width="100%"> 
<tr><td class="content_title"><script>dw(MM_port_forwarding)</script></td></tr>
<tr id="div_content_help"><td class="content_help"><script>dw(MSG_port_forwarding)</script></td></tr>
<tr><td><hr size=1 noshade align=top class=bline></td></tr>
</table>
	<div id="ipmaclist" style=" z-index:999;  width:100%; text-align:center; display: none;position: fixed; border:1px;" >
		<!-- Modal 新增群组-->
		<div style="background-color:#ffffff; width:70%;" data-backdrop="static" >
			<div style="width: 700px;height: 700px;">
				<div style="text-align: right;">
					<!--<button type="button" class="close" style="text-align: right;" data-dismiss="modal" aria-hidden="true" onclick="displaymodel();">
                        ×</button>-->
					<div style="height: 20px;text-align: left;">
						<span style="text-align: left;" type="button"  ><strong>您可以查看当前客户端MAC信息。</strong></span>
					</div>
					<h4 style="text-align: center;">
						LAN设备列表</h4>
				</div>
				<div id="devicelist" style="text-align: center;">

				</div>
				<div id="button_s" style="text-align: right;">

				</div>
			</div>
		</div>
	</div>
<table border=0 width="100%" style="display: none;"> 
<tr>
<td class="item_left"><script>dw(MM_onoff)</script></td>
<td><select	id="enabled" name="enabled" onChange="updateState()">
<option value="0"><script>dw(MM_disable)</script></option>
<option value="1"><script>dw(MM_enable)</script></option>
</select></td>
</tr>
<tr><td colspan="2"><hr size=1 noshade align=top class=bline></td></tr>
</table>

<br />
<table border=0 width="100%"> 
<tr><td colspan="2"><b><script>dw(MM_add_rule)</script></b></td></tr>
<tr id="div_addline"><td colspan="2"><hr size=1 noshade align=top class=bline></td></tr>
<tr>
<td class="item_left"><script>dw(MM_policy_specify)</script></td>
<td><select id="lan_num" name="lan_num" >
</select></td>
</tr>
<tr>
<td class="item_left"><script>dw(MM_protocol)</script></td>
<td><select id="protocol" name="protocol">
<option selected value="tcp/udp">TCP+UDP</option>
<option value="tcp">TCP</option>
<option value="udp">UDP</option>
</select></td>
</tr>
<tr>
<td class="item_left"><script>dw(MM_ipaddr)</script></td>
<td><input type="text" style="width:33px" id="ip_address0" name="ips" maxlength="3" onKeyDown="return ipVali(event,this.name,0);">.
<input type="text" style="width:33px" id="ip_address1" name="ips" maxlength="3" onKeyDown="return ipVali(event,this.name,1);">.
<input type="text" style="width:33px" id="ip_address2" name="ips" maxlength="3" onKeyDown="return ipVali(event,this.name,2);">.
<input type="text" style="width:33px" id="ip_address3" name="ips" maxlength="3" onKeyDown="return ipVali(event,this.name,3);">
<script> dw('<input id=scan name=scan type=button value="'+BT_scan+'" onClick=arpTblClick(\"/net/arpinfo#flag=3\")>')</script></td>
</tr>
<tr>
<td class="item_left"><script>dw(MM_internal_port)</script></td>
<td><input type="text" maxlength="5" size="5" id="toPort" name="toPort"><span style="display:none">  - <input type="text" maxlength="5" size="5" id="toPort" name="toPort"></span> (1-65535)</td>
</tr>
<tr>
<td class="item_left"><script>dw(MM_external_port)</script></td>
<td><input type="text" maxlength="5" size="5" id="fromPort" name="fromPort"><span style="display:none">  - <input type="text" maxlength="5" size="5" id="wantoPort" name="wantoPort"></span> (1-65535)</td>
</tr>
<tr>
<!-- <td class="item_left"><script>dw(MM_comment)</script></td>
<td><input type="text" id="comment" name="comment" maxlength="20"></td>
</tr> -->
</table>

<table border=0 width="100%"> 
<tr><td><hr size=1 noshade align=top class=bline></td></tr>
<tr><td height="10"></td></tr>
<tr><td align="right"><script>dw('<input type=button class=button value="'+BT_add+'" id="add" name="add">')</script></td></tr>
</table>
</form>

<form method=post name="formPortFwdDel" >
<table border=0 width="100%">
<tr><td colspan="7"><b><script>dw(MM_port_forwarding_table)</script>&nbsp;&nbsp;<script>dw(JS_msg59)</script></b></td></tr>
<tr><td colspan="7"><hr size=1 noshade align=top class=bline></td></tr>
<tr align="center">
<td class="item_center"><b>ID</b></td>
<td class="item_center"><b><script>dw(MM_ipaddr)</script></b></td>
<td class="item_center"><b>网络接口</b></td>
<td class="item_center"><b><script>dw(MM_protocol)</script></b></td>
<td class="item_center"><b><script>dw(MM_internal_port)</script></b></td>
<td class="item_center"><b><script>dw(MM_external_port)</script></b></td>
<td class="item_center"><b><script>dw(MM_select)</script></b></td>
</tr>
</table>
<div style="max-height:250px; overflow:auto">
<table border=0 width="100%">
<tbody id="div_portForwardList">
</tbody>
</table>
</div>
<table border=0 width="100%"> 
<tr><td><hr size=1 noshade align=top class=bline></td></tr>
<tr><td height="10"></td></tr>
<tr><td align="right"><script>dw('<input type=button class=button value="'+BT_delete+'" onClick="cs_filter_del()">&nbsp;&nbsp;&nbsp;&nbsp;\
<input type="button" class="button" value="'+BT_reset+'" id="delresest" name="delreset" onClick="resetForm()">')</script></td></tr>
</table>
</form>
<script>showFooter()</script>
</body></html>
<script>
$(function(){
	get_interface();

	init();

	// 添加IP端口转发
	$('#add').on('click', function(event) {
		var ip_address = '';
		var lan_num    = $('#lan_num').val();
		var protocol   = $('#protocol').val();
		var fromPort  = $('#fromPort').val(); // 本地
		var toPort    = $('#toPort').val(); // 远程
		
		for (var i = 0; i < 4; i++) {
			ip_address += $('input[name="ips"]')[i].value + '.';
		}
		ip_address   = ip_address.substr(0,ip_address.length-1);
		var data     = {"Interface":lan_num,"Protocol":protocol,"RemoteIp":ip_address,"LocalPort":fromPort,"RemotePort":toPort};
		var sub_data = {"action":"addPatItem", "data":data};
		sub_data     = JSON.stringify(sub_data);
		$(":input").attr('disabled',true);
		$.ajax({
			url: '/webapi',
			type: 'POST',
			dataType: 'json',
			data: sub_data,
			success:function(data){
				if (9999 == data.rescode){
					issetLogin();
				}
				if (0 == data.rescode) {
					alert('添加成功！');
				    location.href = location.href;
				} else {
					alert('添加失败！'+data_msg_json[data.rescode]);
				}
				$(":input").attr('disabled',false);
			}
		});
	});
});

function arpTblClick(url) {
	openWindow(url,"_blank",700,400);
}

function displaymodel() {
	//document.getElementById("body_div").style.background = "#999999";
	document.getElementById("ipmaclist").style.display = "none";
}

function sure_select() {
	var info = $("input[name='select_radio']:checked").val();
	var arr = info.split("|");
	var ip_info = arr[0].split(".");
	var mac_info = arr[1].split(":");
	for(var i = 0;i<ip_info.length;i++){
		$("#ip_address"+i).val(ip_info[i]);
	}
	for(var j = 0;j<mac_info.length;j++){
		var x =j+1;
		$("#mac"+x).val(mac_info[j]);
	}
	document.getElementById("ipmaclist").style.display = "none";
}

// 获取网卡接口
function get_interface() {
	var _html = '';
	$.ajax({
		url: '/webapi',
		type: 'POST',
		dataType: 'json',
		data: '{"action":"getStatusInfo"}',
		success:function(data){
			if (9999 == data.rescode){
				issetLogin();
			}
			if (0 == data.rescode) {
				var interface = data.data.interface;
				$.each(interface,function(index, el) {
					if (el){
						if('LAN1' != index.toUpperCase()){
							_html += '<option value="'+index+'">'+index.toUpperCase()+'</option>';
						}
					}

				});
				$('#lan_num').html(_html);
			}
		}
	});
}

function init() {
	$.ajax({
		url: '/webapi',
		type: 'POST',
		dataType: 'json',
		data: '{"action":"getPatStatus"}',
		success:function(data){
			if (9999 == data.rescode){
				issetLogin();
			}
			var _html = '';
			if (0 == data.rescode) {
				var data = data.data;
				if (0 < data.length) {
					for (var i = 0; i < data.length; i++) {
						_html += "<tr align=center >";
						_html += "<td>"+(i+1)+"</td>";
						_html += "<td>"+data[i].RemoteIp+"</td>";
						_html += "<td>"+data[i].Interface+"</td>";
						_html += "<td>"+data[i].Protocol+"</td>";
						_html += "<td>"+data[i].RemotePort+"</td>";
						_html += "<td>"+data[i].LocalPort+"</td>";
						_html += '<td><input type="checkbox" name="rule" value='+data[i].Id+' /></td>';
						_html += "</tr>";
					}
					$('#div_portForwardList').html(_html);
				} else {
					$('#div_portForwardList').html('<tr><td colspan=7>暂无数据！</td></tr>');
				}
			}
		}
	});
}
function cs_filter_del() {
	var filtering_all = $(':input[name="rule"]');
	var del_id = [];
	var one_msg = {};
	filtering_all.each(function(index, el) {
		if (el.checked) {
			one_msg.Id = el.value;
			del_id.push(one_msg);
		}
	});
	if (1 != del_id.length) {
		alert('只能同时选择删除一条规则！');
		return false;
	}
    var sub_data = {"action":"delPatItem", "data":one_msg};
    sub_data = JSON.stringify(sub_data);
	$(":input").attr('disabled',true);
	$.ajax({
		url: '/webapi',
		type: 'POST',
		dataType: 'json',
		data: sub_data,
		success:function(data){
			if (9999 == data.rescode){
				issetLogin();
			}
			if (0 == data.rescode) {
				alert('删除成功！');
			    location.href = location.href;
			} else {
				alert('删除失败！'+data_msg_json[data.rescode]);
			}
			$(":input").attr('disabled',false);
		}
	})
}

</script>