<?php

class ApiError
{
    const ERROR_ZH = array(
        //通用错误
        'ip_error'=>'IP不正确',
        'netmask_error'=>'子网掩码不正确',
        'gateway_error'=>'默认网关不正确',
        'mac_error'=>'MAC地址不正确',
        'interface_error'=>'接口不正确',
        'protocol_error'=>'协议不正确',
        'paramater_error'=>'参数错误',
        'enabled_params_error'=>'开启参数不正确',
        'domain_error'=>'域名不正确',
        'port_error'=>'端口不正确',
        'interface_no_exist'=>'接口不存在',
        'rule_exist'=>'规则已存在',
        'rule_no_exist'=>'规则不存在',
        "interface_param_error"=>"接口参数不正确",

        //DNS
        'enparams_error'=>'开启参数不正确',
        'noset_dns_server'=>'未设置DNS服务器，不能关闭DNS转发功能',
        'domain_exist'=>'覆盖的域名已存在',
        'domain_no_exist'=>'要删除的域名不存在',


        //Firewall
        'type_error'=>'类型不正确',
        'forward_ip_error'=>'转发IP不正确',
        'forward_port_error'=>'转发端口不正确',
        'web_port_error'=>'WEB端口不正确',
        'ssh_port_error'=>'SSH端口不正确',

        //Firmware
        'version_error'=>'版本不正确',
        'upload_firmware_no_exist'=>'上传的固件信息不存在',

        //L2TP
        'server_ip_error'=>'服务器IP不正确',
        'client_start_ip_error'=>'客户端开始IP不正确',
        'client_end_ip_error'=>'客户端结束IP不正确',
        'wins_server_ip_error'=>'Wins服务器IP不正确',
        'dns1_error'=>'DNS1不正确',
        'dns2_error'=>'DNS2不正确',
        'auth_type_error'=>'认证类型不正确',
        'username_error'=>'用户名不正确',
        'password_error'=>'密码不正确',
        'user_ip_error'=>'用户IP不正确',
        'user_exist'=>'用户已存在',
        'user_no_exist'=>'用户不存在',

        //Network
        'lan_interface_no_exist'=>'LAN端口接口不存在',
        'lan_interface_least'=>'LAN端口至少有一个接口',
        'netport_unavailable'=>'网口不可用',
        'update_interface_fail'=>'更新接口网桥的网口失败',
        'clonemac_error'=>'克隆MAC参数错误',

        'interface_name_error'=>'接口名称不正确',
        'dhcp_server_enabled_error'=>'DHCP服务器开启参数不正确',
        'dhcp_pool_start_ip_error'=>'DHCP地址池开始IP不正确',
        'dhcp_pool_end_ip_error'=>'DHCP地址池结束IP不正确',
        'network_card_error'=>'网卡不正确',
        'monitor_ip_error'=>'监视IP不正确',
        'name_and_pwd_no_empty'=>'用户名和密码不能为空',
        'connect_mode_error'=>'连接方式不正确',
        'weight_error'=>'权重不正确(1-4)',
        'priority_error'=>'优先级不正确(1-4)',
        'wan_specify_dns_error'=>'WAN接口指定的DNS不能相同',

        'netcard_unavailable'=>'网卡不可用',
        'get_interface_fail'=>'取接口名称失败',
        'get_ident_fail'=>'取接口标识失败',

        'note_no_empty'=>'备注不能为空',
        'mac_add_rule'=>'该MAC地址已添加过规则',
        'ip_add_rule'=>'该IP地址已添加过规则',
        'no_same_segment'=>'静态DHCP地址需要与lan ip地址同一网段',

        'gw_no_in_segment'=>'网关不在网段内',
        'static_route_no_empty'=>'静态路由描述不能为空',
        'static_route_exist'=>'静态路由已存在',
        'static_route_no_exist'=>'静态路由不存在',

        'net_interface_no_exist'=>'网络接口不存在',
        'net_interface_group'=>'网络接口属于组，不能删除',
        'net_interface_bridge'=>'网络接口属于桥，不能删除',
        'net_interface_gre'=>'网络接口属于gre,不能删除',
        'net_interface_gif'=>'网络接口属于gif,不能删除',
        'net_card_error'=>'网卡不正确',

        "lan_interface_param_error"=>"LAN接口参数不正确！",
        "ip_param_error"=>"IP地址参数不正确！",
        "netmask_param_error"=>"子网掩码参数不正确！",
        "dhcp_server_error"=>"DHCP服务器参数不正确！",
        "lans_param_error"=>"多LAN参数错误！",
        "bind_lan_error"=>"LAN接口绑定参数错误！",
        "dhcp_startip_param_error"=>"DHCP起始IP地址参数不正确！",
        "dhcp_endip_param_error"=>"DHCP结束IP地址参数不正确！",

        "ovpnserver"=>"OpenVPN服务器正在使用该端口，不能删除该端口！",
        "ovpnclient"=>"OpenVPN客户端正在使用该端口，不能删除该端口！",
        "ipsec"=>"IPsec正在使用该端口，不能删除该端口！",
        "dyndns"=>"动态DNS正在使用该端口，不能删除该端口！",
        "wol"=>"局域网唤醒正在使用该端口，不能删除该端口！",
        "staticroute"=>"静态路由设置正在使用该端口，不能删除该端口！",

        //Portal
        'server_type_error'=>'服务类型不正确',
        'idle_error'=>'空闲断开时间不正确（1-300）',
        'upload_loginpage_fail'=>'登录页面上传失败',
        'white_ip_error'=>'IP白名单不正确',
        'white_mac_error'=>'MAC白名单不正确',
        'hotid_no_empty'=>'热点ID不能为空',
        'appid_no_empty'=>'appId不能为空',
        'shopid_no_empty'=>'shopId不能为空',
        'ssid_no_empty'=>'ssid不能为空',
        'secretkey_no_empty'=>'secretkey不能为空',
        'pwd_long_error'=>'密码不正确（6-15）',
        'login_valid_cutoff_error'=>'登录有效截止时间不正确',
        'login_valid_time_error'=>'可登录时间不正确',
        'repeat_login_param_error'=>'可重复登录参数不正确',
        'create_user_fail'=>'创建用户失败',
        'del_user_fail'=>'删除用户失败',
        'update_user_fail'=>'更新用户失败',
        'login_user_no_exist'=>'登录用户不存在',
        'offline_fail'=>'下线失败',
        'wechat_no_del'=>'微信用户不能删除',

        //PPTP
        'encryption_error'=>'加密不正确',
        'username_no_empty'=>'用户名不能为空',
        'password_no_exist'=>'密码不能为空',

        //QOS
        'qos_enabled_error'=>'流量控制开启参数不正确',
        'bandwidth_error'=>'带宽不正确',
        'ip_exist'=>'IP已存在',

        //System
        'time_error'=>'时间不正确',
        'select_time_zone'=>'请选择一个时区！',
        'enter_ntp_server'=>'请输入NTP服务器',
        'min_error'=>'分不正确',
        'hour_error'=>'时不正确',
        'day_error'=>'日不正确',
        'month_error'=>'月不正确',
        'week_error'=>'周不正确',
        'conf_file_no_exist'=>'配置文件不存在',

        //user
        'old_pwd_error'=>'原密码不正确',
        'pwd_modify_fail'=>'修改密码失败',

        //packet
        'file_no_exist'=>'文件不存在',


        //IPSEC
        "addr_fam_error"=>"地址簇参数不合法",
        "protocol_param_error"=>"协议参数不合法",
        "host_addr_param_error"=>"主机地址参数不合法，不是一个合法的IP地址或者CIDR块",
        "port_param_error"=>"端口参数不合法",
        "data_pack_length_error"=>"数据包长度参数不合法",
        'calculation_error'=>'计算参数不合法',

        "key_exchange_error"=>"密钥交换版本参数不正确！",
        "remote_gateway_error"=>"远端网关参数不正确！",
        "descr_long_error"=>"描述长度为1~60个字符！",
        "auth_mode_error"=>"认证方式参数不正确！",
        "my_ident_error"=>"我的标识参数不正确！",
        "p2p_ident_error"=>"对端标识参数不正确！",
        "share_key_no_empty"=>"预共享密钥不能为空！",
        "my_ca_error"=>"我的证书颁发机构参数不正确！",
        "cert_data_error"=>"证书数据参数不正确！",
        "private_key_error"=>"私有密钥数据参数不正确！",
        "encryption_algorithm_error"=>"加密算法参数不正确！",
        "encryption_algorithm_bit_error"=>"加密算法bit参数不正确！",
        "hashi_algorithm_error"=>"哈希算法参数不正确！",
        "dh_key_error"=>"DH 密钥组参数不正确！",
        "life_time_gt600"=>"生命周期参数为大于600秒的数字！",
        "repeat_key_error"=>"重复密钥参数不正确！",
        "repeat_auth_error"=>"重复认证参数不正确！",
        "tunnel_isolation_error"=>"隧道隔离参数不正确！",
        "mobike_error"=>"MOBIKE参数不正确！",
        "p2p_delay_error"=>"对端死亡检测参数不正确！",
        "p2p_delay_range"=>"请求对等点确认之间的延迟时间范围为2~100的数字！",
        "allow_fail_times"=>"断开连接之前允许的连续失败次数的范围为2~1000次！",
        "this_data_no_exist"=>"该数据不存在！",
        "negotiation_mode_error"=>"协商模式参数不正确！",

        "phase1_no_exist"=>"该Phase1数据不存在！",

        "mode_param_error"=>"模式参数不正确！",
        "descr_range_1_60"=>"描述字符范围为1~60个字符！",
        "local_network_error"=>"本地网络类型参数不正确！",
        "local_address_error"=>"本地网络地址必须是个合法的IP地址！",
        "local_netmask_range_8_32"=>"本地子网掩码长度为8~32！",
        "remote_netmask_error"=>"远端子网参数不正确！",
        "remote_netmask_addr_error"=>"远端子网地址必须是个合法的IP地址！",
        "remote_netmask_range_8_32"=>"远端子网掩码长度为8~32！",
        "protocol_param_error"=>"协议参数不正确！",
        "pfs_key_group_error"=>"PFS密钥组参数不正确！",
        "life_time_is_int"=>"生命周期必须为整数！",
        "ping_host_error"=>"自动ping主机必须是一个合法的IP地址！",
        "spd_error"=>"SPD参数不正确！",

        "this_data_already_or_no_exist"=>"该数据已删除或不存在！",
        "del_fail"=>"删除失败！",

        "ikeid_error"=>"ikeid参数不正确！",
        "uniqid_error"=>"uniqid参数不正确！",

        //OpenVPN
        "params_error"=>"参数不正确",
        "enabled_param_error"=>"开启参数不正确",
        "server_mode_error"=>"服务器模式不正确",
        "port_range_1_65535"=>"本地端口范围为1~65535",
        "device_mode_error"=>"设备模式参数不正确",
        "dh_length_error"=>"DH参数长度参数不正确",


        "certification_algorithm_error"=>"认证摘要算法参数不正确",
        "hardware_encryption_error"=>"硬件加密参数不正确",
        "certificate_depth_error"=>"证书深度参数不正确",
        "network_tunnelv4_error"=>"IPv4隧道网络参数不正确",
        "local_networkv4_error"=>"IPv4本地网络参数不正确",
        "remote_networkv4_error"=>"IPv4远程网络参数不正确",
        "concurrent_range_1_1024"=>"并发连接参数范围为1~1024",
        "compressed_error"=>"压缩参数不正确",
        "dns_server_error"=>"DNS服务器参数不正确",
        "ntp_server_error"=>"NTP服务器参数不正确",
        "redundancy_level_error"=>" 冗余级别参数不正确",
        "certificate_error"=>"对等证书颁发机构参数不正确",
        "client_ca_error"=>"客户端证书参数不正确",
        "private_key_data_error"=>"私有密钥数据参数不正确",
        "certificate_authority_error"=>"对等证书颁发机构参数不正确",

        "remote_server_addr_no_empty"=>"远程服务器域名或地址不能为空",
        "remote_server_port_error"=>"远程服务器端口不正确",
        "retry_dns_error"=>"重试DNS解析参数不正确",
        "proxy_port_error"=>"代理端口参数不正确",
        "proxy_auth_error"=>"代理验证额外选项认证方式不正确",
        "username_pwd_no_empty"=>"用户名或密码不能为空",
        "local_port_range_1_65535"=>"本地端口范围为1~65535",
        "renegotiate_param_error"=>"重新协商时间ca参数不正确",
        "certificate_auth_error"=>"对等证书颁发机构参数不正确",
        "peer_certificate_auth_error"=>"对等证书颁发机构参数不正确",
        "pre_share_key_no_empty"=>"预共享密钥不能为空",
        "encryp_algorithm_error"=>"加密算法参数不正确",
        "Certification_algorithm_error"=>"认证摘要算法参数不正确",
        "hard_out_limit_error"=>"硬限制外出带宽参数不正确",
        "server_type_param_error"=>"服务类型参数不正确",
        "withdraw_route_error"=>"不要撤出路由参数不正确",
        "add_or_remove_error"=>"不要添加/删除路由参数不正确",
        "password_no_empty"=>"密码不能为空",
        "intercepty_connect_error"=>"拦截连接参数不正确",
        "tunnelv4_network_error"=>"IPv4隧道网络参数不正确，请使用CIDR表示（例如10.0.8.0/24），子网长度为1~30",
        "localv4_network_error"=>"IPv4本地网络参数不正确，请使用CIDR表示，多个CIDR用逗号分隔",
        "remotev4_network_error"=>"IPv4远程网络参数不正确，请使用CIDR表示，多个CIDR用逗号分隔",
        "redirect_gateway_error"=>"重定向网关参数不正确",
        "server_define_error"=>"服务器定义参数不正确",
        "time_server_error"=>"时间服务器参数不正确",
        "create_user_ca_error"=>"用户证书创建失败",
        "export_cfg_error"=>"导出配置参数错误",
        "openvpn_group_error"=>"OpenVPN群组不存在",
        "user_no_in_group"=>"该用户不属于OpenVPN群组",
        "export_conf_error"=>"导出配置失败",

        //TRAFFIC
        "param_error"=>"参数不正确",
        "bandwidth_param_error"=>"带宽参数不正确",
        "bandwidth_unit_error"=>"带宽单位参数不正确",
        "queue_error"=>"队列参数不正确",
        "queue_range_2_100"=>"队列参数不正确，范围为2~100",
        "mask_error"=>"掩码参数不正确",
        "sched_type_error"=>"调度程序类型参数不正确",
        "fqcodel_enabled_error"=>"(FQ-)CoDel开启参数不正确",
        "fqcodel_target_error"=>"(FQ-)CoDel目标参数不正确",
        "fqcodel_interval_error"=>"(FQ-)CoDel间隔参数不正确",
        "fqcodel_ecn_error"=>"(FQ-)CoDel ECN参数不正确",
        "fqcodel_quantity_error"=>"FQ-CoDel量参数不正确",
        "fqcodel_limit_error"=>"FQ-CoDel限制参数不正确",
        "fqcodel_flows_error"=>"FQ-CoDel流参数不正确",
        "pipe_no_exist"=>"管道不存在",
        "descr_error"=>"描述参数不正确",
        "pipe_param_error"=>"管道参数不正确",
        "weight_param_error"=>"权重参数不正确",
        "mask_param_error"=>"掩码参数不正确",
        "enabled_codel_error"=>"启用CoDel参数不正确",
        "queue_no_exist"=>"队列不存在",
        "sequence_error"=>"序列不正确",
        "interface2_param_error"=>"接口2参数不正确",
        "source_error"=>"源参数不正确",
        "invert_source_error"=>"反转源参数不正确",
        "source_port_error"=>"源端口参数不正确",
        "dest_param_error"=>"目的地参数不正确",
        "invert_dest_error"=>"反转目的地参数不正确",
        "dest_port_error"=>"目的端口参数不正确",
        "dire_error"=>"方向参数不正确",
        "target_param_error"=>"目标参数不正确",
        "target_no_exist"=>"目标参数不存在",

        //PROXY
        "enabled_access_log_error"=>"启用访问日志记录参数不正确",
        "enabled_storage_error"=>"启用储存日志记录参数不正确",
        "enabled_dnsv4_error"=>"首先启用DNS v4参数不正确",
        "xff_header_error"=>"X-Forwarded-For标题处理参数不正确",
        "url_empty_error"=>"URI的空白处理参数不正确",
        "inhibite_version_error"=>"抑制版本字符串参数不正确",
        "admin_email_error"=>"管理员的电子邮件参数不正确",
        "memory_cache_range_128_2048"=>"内存高速缓存大小范围为：128~2048",
        "enabled_linux_pack_error"=>"启用Linux包缓存参数不正确",
        "enabled_win_pack_error"=>"启用Windows包缓存参数不正确",
        "enabled_traffic_error"=>"启用流量管理参数不正确",
        "max_down_size_error"=>"最大下载大小参数不正确",
        "max_upload_size_error"=>"最大上传大小参数不正确",
        "total_bw_limit_error"=>"总带宽限制参数不正确",
        "host_adjust_param_error"=>"每个主机带宽调节参数不正确",
        "host_adjust_descr"=>"每个主机带宽调节参数和总带宽限制参数只能同时为空，或同时填写",
        "proxy_port_ssl_range_1_65535"=>"代理端口与SSL代理端口范围为：1~65535",
        "enabled_ssl_error"=>"启用SSL检验参数不正确",
        "sni_record_error"=>"仅记录SNI信息参数不正确",
        "sslcache_sslca_error"=>"SSL缓存大小或SSL证书工作者参数不正确",
        "allow_interface_error"=>"允许接口子网参数不正确",
        "enabled_transpare_http_proxy_error"=>"启用透明HTTP代理参数不正确",
        "allow_dest_tcp_port_error"=>"允许的目的TCP端口参数不正确",
        "allow_ssl_port_error"=>"允许的SSL端口参数不正确",

        "icap_enabled_error"=>"病毒检测开启参数错误",
        "icap_access_log_error"=>"ICAP访问日志开启参数错误",
        "icap_cache_error"=>"ICAP缓存参数不正确",
        "max_file_size_error"=>"病毒检测最大扫描文件参数不正确",
        "scan_exe_file_error"=>"扫描可执行文件参数不正确",
        "scan_exe_link_file_error"=>"扫描可执行和链接格式",
        "scan_ole2_error"=>"扫描OLE2文件参数不正确",
        "scan_pdf_error"=>"扫描PDF文件参数不正确",
        "scan_swf_error"=>"扫描SWF文件参数不正确",
        "scan_doc_error"=>"扫描XMLDOCS文件参数不正确",
        "scan_hwp3_error"=>"扫描HWP3文件参数不正确",
        "scan_html_error"=>"扫描HTML文件参数不正确",
        "scan_archives_error"=> "Scanned archives file parameters are incorrect",
        "icap_admin_email_error"=>"ICAP管理员邮箱参数错误",

        "memory_short_note"=>"内存不足无法开启病毒检测功能,需要大于2G才能运行",

        //WOL
        "mac_addr_param_error"=>"MAC地址参数不正确",
        "descr_param_error"=>"描述参数不正确",
        "wakeup_fail"=>"唤醒失败",

        //DDNS
        "from_interface_update_error"=>"从接口发送更新参数不正确！",
        "host_name_empty"=>"主机名不能为空！",
        "mx_error"=>"MX参数不正确！",
        "wildcard_error"=>"通配符参数不正确！",
        "verbose_log_error"=>"verbose日志参数不正确！",
        "descr_length60"=>"描述不能超过60字符！",
        "url_no_empty"=>"更新URL不能为空！",
        "mandatory_parsingv4_error"=>"强制IPv4解析参数不正确！",
        "ssl_check_error"=>"SSL对端校验参数不正确！",

        "zoneid_error"=>"区域ID参数不正确！",

        "this_data_no_exist_or_delete"=>"该数据不存在或已删除！",

        //RADIUS
        "vlan_error"=>"VLAN参数不正确！",
        "wispr_error"=>"WISPr参数不正确！",
        "chillispot_error"=>"ChilliSpot参数不正确！",
        "session_limit_error"=>"会话限制参数不正确！",
        "log_type_error"=>"日志类型参数不正确！",
        "log_auth_error"=>"日志认证请求参数不正确",
        "error_pwd_save_error"=>"错误密码保存到日志参数不正确！",
        "correct_pwd_save_error"=>"正确密码保存到日志参数不正确！",
        "default_eap_error"=>"默认EAP类型参数不正确",

        "username_param_error"=>"用户名参数不正确！",
        "password_param_error"=>"密码参数不正确！",
        "ip_addr_error"=>"IP地址参数不正确！",
        "wispr_min_upload_error"=>"WISPr最小上传带宽参数不正确！",
        "wispr_max_upload_error"=>"WISPr最大上传带宽参数不正确！",
        "wispr_min_down_error"=>"WISPr最小下载带宽参数不正确！",
        "wispr_max_down_error"=>"WISPr最大下载带宽参数不正确！",
        "chillspot_max_upload_error"=>"ChilliSpot最大上传带宽参数不正确！",
        "chillispot_max_down_error"=>"ChilliSpot最大下载带宽参数不正确！",
        "session_max_limit_error"=>"最大会话限制参数不正确！",
        "username_no_exist"=>"用户不存在！",
        "username_exist"=>"用户已存在！",

        "client_param_error"=>"客户端参数不正确！",
        "client_no_exist"=>"客户端不存在！",

        "ip_network_error"=>"IP地址或网络地址参数不正确！",
        "name_param_error"=>"名称参数不正确！",
        "key_param_error"=>"密钥参数不正确！",
        "client_name_exist"=>"客户端名称已存在！"
    );

    const ERROR_EN = array(
        //通用错误
        'ip_error'=>'IP is incorrect',
        'netmask_error'=>'Subnet mask is incorrect',
        'gateway_error'=>'Default gateway is incorrect',
        'mac_error'=>'Incorrect MAC address',
        'interface_error'=>'Incorrect interface',
        'protocol_error'=>'Incorrect agreement',
        'paramater_error'=>'Paramater Error',
        'enabled_params_error'=>'Incorrect open parameter',
        'domain_error'=>'The domain name is not correct',
        'port_error'=>'Incorrect port',
        'interface_no_exist'=>'Interface does not exist',
        'rule_exist'=>'Rule already exists',
        'rule_no_exist'=>'Rule does not exist',
        "interface_param_error"=> "The interface parameter is incorrect",

        //DNS
        'enparams_error'=>'Incorrectly opening parameters',
        'noset_dns_server'=>'DNS server is not set and DNS forwarding cannot be shut down',
        'domain_exist'=>'The covered domain name has already existed',
        'domain_no_exist'=>'The domain name to be deleted does not exist',

        //Firewall
        'type_error'=>'Incorrect type',
        'forward_ip_error'=>'Forwarding IP is incorrect',
        'forward_port_error'=>'Incorrect forwarding port',
        'web_port_error'=>'WEB port is incorrect',
        'ssh_port_error'=>'SSH port is incorrect',

        //Firmware
        'version_error'=>'Incorrect version',
        'upload_firmware_no_exist'=>'The uploaded firmware information does not exist',


        //L2TP
        'server_ip_error'=>'Server IP is incorrect',
        'client_start_ip_error'=>'The client starts IP incorrectly',
        'client_end_ip_error'=>'Client end IP is incorrect',
        'wins_server_ip_error'=>'Wins server IP is incorrect',
        'dns1_error'=>'DNS1 is incorrect',
        'dns2_error'=>'DNS2 is incorrect',
        'auth_type_error'=>'Incorrect authentication type',
        'username_error'=>'Incorrect username',
        'password_error'=>'Incorrect password',
        'user_ip_error'=>'User IP is incorrect',
        'user_exist'=>'The user has already existed',
        'user_no_exist'=>'user does not exist',

        //Network
        'lan_interface_no_exist'=>'Lan port interface does not exist',
        'lan_interface_least'=>'Lan port has at least one interface',
        'netport_unavailable'=>'The network port is not available',
        'update_interface_fail'=>'Failed to update network port of interface bridge',
        'clonemac_error'=>'Error cloning MAC parameters',

        'interface_name_error'=>'Incorrect interface name',
        'dhcp_server_enabled_error'=>'DHCP server open parameter is incorrect',
        'dhcp_pool_start_ip_error'=>'DHCP address pool starts IP incorrectly',
        'dhcp_pool_end_ip_error'=>'The DHCP address pool is not correct at the end of the IP',
        'network_card_error'=>'Network card is not correct',
        'monitor_ip_error'=>'Monitoring IP is incorrect',
        'name_and_pwd_no_empty'=>'The username and password can not be empty',
        'connect_mode_error'=>'Incorrect connection mode',
        'weight_error'=>'Incorrect weight (1-4)',
        'priority_error'=>'Incorrect priority (1-4)',
        'wan_specify_dns_error'=>'The WAN interface specifies that the DNS can not be the same',

        'netcard_unavailable'=>'Network card is unavailable',
        'get_interface_fail'=>'Failure to fetch the name of the interface',
        'get_ident_fail'=>'Interface identification failure',

        'note_no_empty'=>'The note can not be empty',
        'mac_add_rule'=>'The MAC address has been added to the rules',
        'ip_add_rule'=>'The IP address has been added to the rules',
        'no_same_segment'=>'The static DHCP address needs the same network segment as the LAN IP address',

        'gw_no_in_segment'=>'The gateway is not within the network segment',
        'static_route_no_empty'=>'Static routing description cannot be empty',
        'static_route_exist'=>'Static routing already exists',
        'static_route_no_exist'=>'Static routing does not exist',

        'net_interface_no_exist'=>'Network interface does not exist',
        'net_interface_group'=>'The network interface belongs to the group and can not be deleted',
        'net_interface_bridge'=>'The network interface belongs to the bridge and can not be deleted',
        'net_interface_gre'=>'The network interface belongs to GRE, which can not be deleted',
        'net_interface_gif'=>'The network interface belongs to GIF, which can not be deleted',
        'net_card_error'=>'Network card is not correct',

        "lan_interface_param_error"=>"LAN interface parameters are not correct!",
        "ip_param_error"=>"The IP address parameter is not correct!",
        "netmask_param_error"=>"The subnet mask is not correct.",
        "dhcp_server_error"=>"DHCP server parameters are not correct!",
        "lans_param_error"=>"Many LAN parameters are wrong!",
        "bind_lan_error"=>"LAN interface binding parameter error!",
        "dhcp_startip_param_error"=>"DHCP starting IP address parameter is incorrect!",
        "dhcp_endip_param_error"=>"DHCP end IP address parameter is incorrect!",

        "ovpnserver"=>"The port is being used by the OpenVPN server, and the port cannot be deleted.",
        "ovpnclient"=>"The port is being used by the OpenVPN client, and the port cannot be deleted.",
        "ipsec"=>"IPsec is using this port and cannot delete the port!",
        "dyndns"=>"Dynamic DNS is using this port and cannot delete the port!",
        "wol"=>"LAN wakeup is using the port and cannot delete the port!",
        "staticroute"=>"Static port settings are using this port, and the port cannot be deleted.",


        //Portal
        'server_type_error'=>'Incorrect service type',
        'idle_error'=>'The idle break time is not correct (1-300)',
        'upload_loginpage_fail'=>'Login page upload failure',
        'white_ip_error'=>'IP white list is not correct',
        'white_mac_error'=>'MAC white list is not correct',
        'hotid_no_empty'=>'Hot ID can not be empty',
        'appid_no_empty'=>'AppId cannot be empty',
        'shopid_no_empty'=>'ShopId cannot be empty',
        'ssid_no_empty'=>'SSID cannot be empty',
        'secretkey_no_empty'=>'secretkey cannot be empty',
        'pwd_long_error'=>'Incorrect password (6-15)',
        'login_valid_cutoff_error'=>'Logon valid cut-off time is incorrect',
        'login_valid_time_error'=>'Incorrectly logon time',
        'repeat_login_param_error'=>'Repeatable logon parameters are incorrect',
        'create_user_fail'=>'Create user failure',
        'del_user_fail'=>'Delete user failure',
        'update_user_fail'=>'Update user failure',
        'login_user_no_exist'=>'Logged in users do not exist',
        'offline_fail'=>'Downline failure',
        'wechat_no_del'=>'Wechat users cannot delete',

        //PPTP
        'encryption_error'=>'Incorrectly encrypted',
        'username_no_empty'=>'The username can not be empty',
        'password_no_exist'=>'The password can not be empty',

        //QOS
        'qos_enabled_error'=>'QOS open parameter is incorrect',
        'bandwidth_error'=>'Incorrect bandwidth',
        'ip_exist'=>'IP already exists',

        //System
        'time_error'=>'Time is not correct',
        'select_time_zone'=>'please choose a time zone!',
        'enter_ntp_server'=>'please enter the NTP server',
        'min_error'=>'Minute is not correct',
        'hour_error'=>'Hour is not correct',
        'day_error'=>'Date is not correct',
        'month_error'=>'Month is not correct',
        'week_error'=>'Week is not right',
        'conf_file_no_exist'=>'Configuration file does not exist',

        //user
        'old_pwd_error'=>'Incorrect original password',
        'pwd_modify_fail'=>'Failure to modify the password',

        //packet
        'file_no_exist'=>'File does not exist',


        //IPSEC
        "addr_fam_error"=>"Illegal address cluster parameter",
        "protocol_param_error"=>"Illegal agreement parameter",
        "host_addr_param_error"=>"The host address parameter is illegal and is not a legal IP address or CIDR block.",
        "port_param_error"=>"Invalid port parameter",
        "data_pack_length_error"=>"Invalid packet length parameter",
        'calculation_error'=>'Invalid calculation parameter',

        "key_exchange_error"=>"The key exchange version of the parameter is incorrect!",
        "remote_gateway_error"=>"The remote gateway parameter is incorrect!",
        "descr_long_error"=>"The length of the description is 1~60 characters!",
        "auth_mode_error"=>"The authentication method is not correct.",
        "my_ident_error"=>"My identification parameter is not correct!",
        "p2p_ident_error"=>"The end identification parameter is incorrect!",
        "share_key_no_empty"=>"The pre shared key cannot be empty!",
        "my_ca_error"=>"My certificate authority has incorrect parameters.",
        "cert_data_error"=>"The certificate data parameters are not correct!",
        "private_key_error"=>"The private key data parameter is incorrect!",
        "encryption_algorithm_error"=>"The encryption algorithm is not correct.",
        "encryption_algorithm_bit_error"=>"The encryption algorithm bit parameter is incorrect!",
        "hashi_algorithm_error"=>"The Hashi algorithm is not correct.",
        "dh_key_error"=>"The DH key group parameters are not correct!",
        "life_time_gt600"=>"The number of life cycle parameters is greater than 600 seconds.",
        "repeat_key_error"=>"The repeat key parameter is incorrect!",
        "repeat_auth_error"=>"The duplication of authentication parameters is not correct!",
        "tunnel_isolation_error"=>"The parameters of the tunnel isolation are not correct!",
        "mobike_error"=>"The MOBIKE parameter is not correct!",
        "p2p_delay_error"=>"The end of the death detection parameters are not correct!",
        "p2p_delay_range"=>"The number of delay requests between request peers is 2~100.",
        "allow_fail_times"=>"The number of consecutive failures allowed before disconnection is 2~1000 times.",
        "this_data_no_exist"=>"The data does not exist!",
        "negotiation_mode_error"=>"The negotiation mode parameters are not correct!",
        "phase1_no_exist"=>"The Phase1 data does not exist!",

        "mode_param_error"=>"The mode parameters are not correct!",
        "descr_range_1_60"=>"Description character range is 1~60 character!",
        "local_network_error"=>"The local network type parameter is not correct!",
        "local_address_error"=>"Local network address must be a legitimate IP address.",
        "local_netmask_range_8_32"=>"The local subnet mask length is 8~32!",
        "remote_netmask_error"=>"The parameters of the remote subnet are not correct!",
        "remote_netmask_addr_error"=>"The remote subnet address must be a legitimate IP address.",
        "remote_netmask_range_8_32"=>"The remote subnet mask length is 8~32!",
        "protocol_param_error"=>"The protocol parameters are not correct!",
        "pfs_key_group_error"=>"The PFS key group parameters are not correct!",
        "life_time_is_int"=>"The lifecycle must be an integer!",
        "ping_host_error"=>"Automatic Ping host must be a legitimate IP address.",
        "spd_error"=>"The SPD parameter is not correct!",


        "this_data_already_or_no_exist"=>"This data has been deleted or not!",
        "del_fail"=>"Delete the failure!",


        "ikeid_error"=>"The ikeid parameter is not correct!",
        "uniqid_error"=>"The uniqid parameter is not correct!",


        //OpenVPN
        "params_error"=>"Parameter is not correct",
        "enabled_param_error"=>"Open the parameter is not correct",
        "server_mode_error"=>"Server mode is not correct",
        "port_range_1_65535"=>"The local port range is 1 ~ 65535",
        "device_mode_error"=>"Equipment model parameters is not correct",
        "dh_length_error"=>"DH parameters length is not correct",


        "certification_algorithm_error"=>"Certification of the algorithm parameter is not correct",
        "hardware_encryption_error"=>"Hardware encryption parameters is not correct",
        "certificate_depth_error"=>"Certificate of depth parameter is not correct",
        "network_tunnelv4_error"=>"IPv4 tunnel network parameters is not correct",
        "local_networkv4_error"=>"IPv4 local network parameter is not correct",
        "remote_networkv4_error"=>"IPv4 remote network parameters is not correct",
        "concurrent_range_1_1024"=>"Concurrent connection parameters range is 1 ~ 1024",
        "compressed_error"=>"Compressed parameters is not correct",
        "dns_server_error"=>"The DNS server parameter is not correct",
        "ntp_server_error"=>"The NTP server parameter is not correct",
        "redundancy_level_error"=>" Redundancy level parameter is not correct",
        "certificate_error"=>"Peer certificate issuing authority parameter is not correct",
        "client_ca_error"=>"The client certificate parameter is not correct",
        "private_key_data_error"=>"The private key parameter data is not correct",
        "certificate_authority_error"=>"Peer certificate issuing authority parameter is not correct",

        "remote_server_addr_no_empty"=>"The remote server domain name or address can't be empty",
        "remote_server_port_error"=>"The remote server port is not correct",
        "retry_dns_error"=>"Retry the DNS parameters is not correct",
        "proxy_port_error"=>"Proxy port parameter is not correct",
        "proxy_auth_error"=>"Proxy authentication options additional authentication is not correct",
        "username_pwd_no_empty"=>"The username or password cannot be empty",
        "local_port_range_1_65535"=>"The local port range is 1 ~ 65535",
        "renegotiate_param_error"=>"To renegotiate the time parameter is not correct",
        "certificate_auth_error"=>"Peer certificate issuing authority parameter is not correct",
        "peer_certificate_auth_error"=>"Peer certificate issuing authority parameter is not correct",
        "pre_share_key_no_empty"=>"The pre shared key cannot be empty",
        "encryp_algorithm_error"=>"Encryption algorithm parameters is not correct",
        "Certification_algorithm_error"=>"Certification of the algorithm parameter is not correct",
        "hard_out_limit_error"=>"Out the hard limit bandwidth parameter is not correct",
        "server_type_param_error"=>"Service type parameter is not correct",
        "withdraw_route_error"=>"Don't withdraw from routing parameters is not correct",
        "add_or_remove_error"=>"Don't add/remove routing parameters is not correct",

        "password_no_empty"=>"The password can not be empty.",
        "intercepty_connect_error"=>"Intercepting connection parameter is incorrect",
        "tunnelv4_network_error"=>"IPv4 tunnel network parameters are incorrect, please use CIDR to represent (for example 10.0.8.0/24), and the subnet length is 1~30",
        "localv4_network_error"=>"IPv4 local network parameters are incorrect. Use CIDR to indicate that multiple CIDR is separated by commas.",
        "remotev4_network_error"=>"IPv4 remote network parameters are incorrect. Use CIDR to indicate that multiple CIDR are separated by commas.",
        "redirect_gateway_error"=>"The redirection gateway parameter is incorrect",
        "server_define_error"=>"The server definition parameter is incorrect",
        "time_server_error"=>"The parameters of the time server are not correct",
        "create_user_ca_error"=>"The user certificate creation failed",



        "export_cfg_error"=>"Exporting configuration parameter error",
        "openvpn_group_error"=>"OpenVPN groups do not exist.",
        "user_no_in_group"=>"This user does not belong to the OpenVPN group.",
        "export_conf_error"=>"Export configuration failure",

        //TRAFFIC
        "param_error"=> "The parameter is incorrect",
        "bandwidth_param_error"=> "The bandwidth parameter is incorrect",
        "bandwidth_unit_error"=> "Incorrect bandwidth unit parameter",
        "queue_error"=> "The queue parameter is incorrect",
        "queue_range_2_100"=> "The queue parameters are incorrect, ranging from 2 to 100",
        "mask_error"=> "The mask parameter is incorrect",
        "sched_type_error"=> "The scheduler type parameter is incorrect",
        "fqcodel_enabled_error"=> "(FQ-)CoDel open parameter is incorrect",
        "fqcodel_target_error"=> "(FQ-)CoDel target parameter is incorrect",
        "fqcodel_interval_error"=> "(FQ-) CoDel interval parameter is incorrect",
        "fqcodel_ecn_error"=> "(FQ-)CoDel ECN parameter is incorrect",
        "fqcodel_quantity_error"=> "FQ-CoDel quantity parameter is incorrect",
        "fqcodel_limit_error"=> "The FQ-CoDel restriction parameter is incorrect",
        "fqcodel_flows_error"=> "The FQ-CoDel stream parameter is incorrect",
        "pipe_no_exist"=> "The pipe does not exist",
        "descr_error"=> "The description parameter is incorrect",
        "pipe_param_error"=> "The pipeline parameter is incorrect",
        "weight_param_error"=> "The weight parameter is incorrect",
        "mask_param_error"=> "The mask parameter is incorrect",
        "enabled_codel_error"=> "Incorrect CoDel parameter is enabled",
        "queue_no_exist"=> "Queue does not exist",
        "sequence_error"=> "The sequence is incorrect",
        "interface2_param_error"=> "Interface 2 parameter is incorrect",
        "source_error"=> "The source parameter is incorrect",
        "invert_source_error"=> "Invert source parameter is incorrect",
        "source_port_error"=> "The source port parameter is incorrect",
        "dest_param_error"=> "The destination parameter is incorrect",
        "invert_dest_error"=> "Invert destination parameter is incorrect",
        "dest_port_error"=> "The destination port parameter is incorrect",
        "dire_error"=> "The direction parameter is incorrect",
        "target_param_error"=> "The target parameter is incorrect",
        "target_no_exist"=> "The target parameter does not exist",


        //PROXY
        "enabled_access_log_error"=> "Enabling Access Logging Parameters Is Incorrect",
        "enabled_storage_error"=> "Enabling Incorrect Storage Logging Parameters",
        "enabled_dnsv4_error"=> "Incorrect DNS v4 parameter was first enabled",
        "xff_header_error"=> "The X-Forwarded-For header processing parameter is incorrect",
        "url_empty_error"=> "The NULL blank processing parameter is incorrect",
        "inhibite_version_error"=> "Inhibited version string parameter is incorrect",
        "admin_email_error"=> "The administrator's email parameter is incorrect",
        "memory_cache_range_128_2048"=> "The memory cache size range is 128~2048",
        "enabled_linux_pack_error"=> "Invalid Linux Package Cache Parameter Enabled",
        "enabled_win_pack_error"=> "Enable Windows Package Cache Parameters Incorrect",
        "enabled_traffic_error"=> "Enable traffic management parameters incorrect",
        "max_down_size_error"=> "The maximum download size parameter is incorrect",
        "max_upload_size_error"=> "The maximum upload size parameter is incorrect",
        "total_bw_limit_error"=> "The total bandwidth limit parameter is incorrect",
        "host_adjust_param_error"=> "Each host bandwidth adjustment parameter is incorrect",
        "host_adjust_descr"=>"Each host bandwidth adjustment parameter and total bandwidth limit parameter can only be empty or filled simultaneously",
        "proxy_port_ssl_range_1_65535"=> "Proxy port and SSL proxy port range=> 1~65535",
        "enabled_ssl_error"=> "Invalid SSL validation parameters enabled",
        "sni_record_error"=> "The only record of SNI information parameters is incorrect",
        "sslcache_sslca_error"=> "The SSL cache size or SSL certificate worker parameters are incorrect",
        "allow_interface_error"=> "Allowable interface subnet parameters are incorrect",
        "enabled_transpare_http_proxy_error"=> "Enabling Transparent HTTP Proxy Parameters Is Incorrect",
        "allow_dest_tcp_port_error"=> "The allowed destination TCP port parameter is incorrect",
        "allow_ssl_port_error"=> "The allowed SSL port parameters are incorrect",

        "icap_enabled_error"=> "Virus detection opening parameter error",
        "icap_access_log_error"=> "ICAP access log opens parameter errors",
        "icap_cache_error"=> "ICAP cache parameter is incorrect",
        "max_file_size_error"=> "Virus detection maximum scan file parameter is incorrect",
        "scan_exe_file_error"=> "Scanned executable file parameters are incorrect",
        "scan_exe_link_file_error"=> "Scan executable and link format",
        "scan_ole2_error"=> "Scanned OLE2 file parameters are incorrect",
        "scan_pdf_error"=> "Scanned PDF file parameters are incorrect",
        "scan_swf_error"=> "Scanned SWF file parameters are incorrect",
        "scan_doc_error"=> "Scanned XMLDOCS file parameters are incorrect",
        "scan_hwp3_error"=> "Scanned HWP3 file parameters are incorrect",
        "scan_html_error"=> "Scanned HWP3 file parameters are incorrect",
        "scan_archives_error"=> "Scanned archives file parameters are incorrect",
        "icap_admin_email_error"=> "ICAP administrator mailbox parameter error",
        "memory_short_note"=>"Lack of memory can not open virus detection function.It takes more than 2g to run.",

        //WOL
        "mac_addr_param_error"=> "The MAC address parameter is incorrect",
        "descr_param_error"=> "The description parameter is incorrect",
        "wakeup_fail"=> "Wakeup failed",

        //DDNS
        "from_interface_update_error"=>"Send updates from the interface is not correct!",
        "host_name_empty"=>"The host name is not empty!",
        "mx_error"=>"The MX parameter is not correct!",
        "wildcard_error"=>"The parameter of the wildcard is not correct!",
        "verbose_log_error"=>"The verbose log parameter is not correct!",
        "descr_length60"=>"The description cannot be more than 60 characters!",
        "url_no_empty"=>"Update URL can not be empty!",
        "mandatory_parsingv4_error"=>"Mandatory IPv4 parsing parameters are incorrect!",
        "ssl_check_error"=>"SSL to the end check parameter is incorrect!",

        "zoneid_error"=>"The parameters of the area ID are not correct!",

        "this_data_no_exist_or_delete"=>"The data does not exist or has been deleted!",


        //RADIUS
        "vlan_error"=>"The VLAN parameter is not correct!",
        "wispr_error"=>"The WISPr parameter is not correct!",
        "chillispot_error"=>"The ChilliSpot parameter is not correct!",
        "session_limit_error"=>"Session restriction parameter is incorrect!",
        "log_type_error"=>"The log type parameter is incorrect!",
        "log_auth_error"=>"Log authentication request parameters are not correct",
        "error_pwd_save_error"=>"Incorrect password saved to log parameter is incorrect!",
        "correct_pwd_save_error"=>"Correct password saved to log parameter is incorrect!",
        "default_eap_error"=>"The default EAP type parameter is incorrect.",

        "username_param_error"=>"The username parameter is not correct!",
        "password_param_error"=>"The password parameters are not correct!",
        "ip_addr_error"=>"The IP address parameter is not correct!",

        "wispr_min_upload_error"=>"WISPr minimum upload bandwidth parameter is incorrect!",
        "wispr_max_upload_error"=>"The maximum upload bandwidth parameter of WISPr is incorrect.",
        "wispr_min_down_error"=>"WISPr's minimum download bandwidth parameter is incorrect.",
        "wispr_max_down_error"=>"WISPr's maximum download bandwidth parameter is incorrect.",
        "chillspot_max_upload_error"=>"The maximum upload bandwidth parameter of ChilliSpot is incorrect.",
        "chillispot_max_down_error"=>"ChilliSpot's maximum download bandwidth parameter is incorrect.",
        "session_max_limit_error"=>"The maximum session restriction parameter is incorrect!",
        "username_no_exist"=>"The user does not exist!",
        "username_exist"=>"The user has already existed!",

        "client_param_error"=>"The client parameters are not correct!",
        "client_no_exist"=>"The client does not exist!",

        "ip_network_error"=>"IP address or network address parameter is incorrect!",
        "name_param_error"=>"The name parameter is not correct!",
        "key_param_error"=>"The key parameter is not correct!",
        "client_name_exist"=>"The name of the client already exists!",

    );
}