<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8"> 
<link href="/css/style.css" rel="stylesheet" type="text/css">
<script language="javascript" src="/js/language.js"></script>
<script language="javascript" src="/js/jcommon.js"></script>
</head>

<body>
<table width="100%" border="0" cellspacing="0" cellpadding="0">
<tr>
<td class="bottom_left">&nbsp;</td>
<td class="bottom_center1">&nbsp;</td>
<td class="bottom_center1">
<script>
	var curDate = new Date();
	dw(MM_Copyright_Left)+document.write(curDate.getFullYear())+dw(MM_Copyright_Right);
</script>
</td>
<td class="bottom_center1">&nbsp;</td>
<td class="bottom_right">&nbsp;</td>
</tr>
</table>
</body>
</html>
