<!DOCTYPE html>
<html lang="en">
	<head>
		<meta http-equiv="Pragma" content="no-cache">
		<meta http-equiv="Expires" content="-1">
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
		<link href="/css/normal_ws.css" rel="stylesheet" type="text/css">
		<link href="/css/style.css" rel="stylesheet" type="text/css">
		<script language="javascript" src="/js/jquery.min.js"></script>
		<script language="javascript" src="/js/language.js"></script>
		<script language="javascript" src="/js/json2.min.js"></script>
		<script language="javascript" src="/js/jcommon.js"></script>
	</head>
	<body >
		<table width="100%" border="0" cellspacing="0" cellpadding="0">
			<tr>
				<td class="title_down_left" id="ProductModel">CSG2000P <?php echo $this->config->csg2000p->version?>.<?php echo $this->config->csg2000p->build_date?></td>
				<td class="title_down_center" align="right">&nbsp;</td>
				<td class="title_down_right" align="right">
					<span id="div_multi_language" style="display:none;">
						<img id="language" src="/images/language_cn.gif" border="0" align="absmiddle" style="cursor:pointer">&nbsp;&nbsp;
					</span>
					<span id="div_help">
						<a id="helpUrl" href="http://www.totolink.cn" target="_blank">
							<img id="help" src="/images/help_cn.gif" border="0" align="absmiddle">
						</a>
					</span>&nbsp;&nbsp;&nbsp;&nbsp;
				</td>
			</tr>
		</table>
	</body>
</html>